/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Contract, Interface } from "ethers";
const _abi = [
    {
        inputs: [
            {
                internalType: "bytes32",
                name: "recordIdHash",
                type: "bytes32",
            },
            {
                internalType: "bytes32",
                name: "userIdHash",
                type: "bytes32",
            },
        ],
        name: "isActiveSubject",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
export class HealthRecordCoreInterface__factory {
    static createInterface() {
        return new Interface(_abi);
    }
    static connect(address, runner) {
        return new Contract(address, _abi, runner);
    }
}
HealthRecordCoreInterface__factory.abi = _abi;
