/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { HealthRecordCoreInterface__factory } from "./HealthRecordCoreInterface__factory";
export { MemberRoleManager__factory } from "./MemberRoleManager__factory";
export { MemberRoleManagerInterface__factory } from "./MemberRoleManagerInterface__factory";
