/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as healthRecordCoreSol from "./HealthRecordCore.sol";
export type { healthRecordCoreSol };
import type * as memberRoleManagerSol from "./MemberRoleManager.sol";
export type { memberRoleManagerSol };
export type { BelrosePaymaster } from "./BelrosePaymaster";
