"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserOperationLib__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [],
        name: "PAYMASTER_DATA_OFFSET",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "PAYMASTER_POSTOP_GAS_OFFSET",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "PAYMASTER_VALIDATION_GAS_OFFSET",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
const _bytecode = "0x608080604052346100195760b0908161001e823930815050f35b5f80fdfe60808060405260043610156011575f80fd5b5f3560e01c90816325093e1b14606757508063b29a8ff41460525763ede31502146039575f80fd5b5f366003190112604e57602060405160348152f35b5f80fd5b5f366003190112604e57602060405160148152f35b5f366003190112604e5780602460209252f3fea26469706673582212203f65a60b09b2f86317639fbf7d780ac8609954c9e2908b27e186e0625ac1f19664736f6c63430008180033";
const isSuperArgs = (xs) => xs.length > 1;
class UserOperationLib__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    connect(runner) {
        return super.connect(runner);
    }
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.UserOperationLib__factory = UserOperationLib__factory;
UserOperationLib__factory.bytecode = _bytecode;
UserOperationLib__factory.abi = _abi;
//# sourceMappingURL=UserOperationLib__factory.js.map