// src/components/site/FAQ/faqData.ts

/**
 * FAQ questions for site
 */

import React from 'react';

export interface FAQItem {
  q: string;
  a: React.ReactNode;
  homepage?: boolean;
}

type FAQData = Record<string, FAQItem[]>;

export const faqs: FAQData = {
  'Getting Started': [
    {
      q: 'What is Belrose and who is it for?',
      a: 'Belrose is a technology and incentivization infrastructure that gives people sovereignty over their health data. It is for anyone who wants to take control of their health data — whether you are managing a chronic condition, keeping track of family records, or simply want a complete picture of your health history in one place.',
      homepage: true,
    },
    {
      q: 'How is Belrose different from other health record apps?',
      a: "Other health record apps give you 'access' or a 'portal' to your records. Belrose gives you true ownership. Correct mistakes, manage access, donate your data, sell your data, all of this is possible with Belrose's data protocol.",
      homepage: true,
    },
    {
      q: 'Is Belrose free to use?',
      a: 'Managing your own records is free and always will be. We plan to offer premium features for those who want additional storage, data monetisation, and advanced health services.',
      homepage: true,
    },
    {
      q: 'How do I get my records into Belrose?',
      a: (
        <p>
          Under <strong>GDPR Article 15</strong> (UK/EU) and <strong>HIPAA 45 CFR §164.524</strong>{' '}
          (US), you have a legal right to request your health records from any provider. Belrose
          helps you exercise that right — we send the request on your behalf and import your records
          once received. You can also upload documents manually in any format.
        </p>
      ),
    },
    {
      q: 'What types of records can I store?',
      a: 'Anything. GP notes, hospital discharge summaries, lab results, imaging reports, prescriptions, vaccination records, dental records, and even self-reported data like fitness metrics or mental health journals.',
    },
    {
      q: 'What countries is Belrose available in?',
      a: 'Our main focus is currently the US and UK, but Belrose is available to anyone in any country who wants to manage their own health records.',
      homepage: true,
    },
  ],

  'The Belrose Protocol': [
    {
      q: 'What is the Belrose Protocol?',
      a: "The Belrose Protocol is a record storage and management procedure we developed. It involves collecting a patient's records, standardising them into interoperable FHIR format, storing them on client-side encrypted servers, sharing them as desired, and using a distributed network to store hashes for verification.",
      homepage: true,
    },
    {
      q: 'How can a doctor or third party rely on a record that is completely controlled by the patient? The patient could be lying.',
      a: 'Our protocol involves storing hashes of the record data on a distributed network alongside verifications from trusted parties. This allows future viewers of patient-provided records to know that the record has not been tampered with.',
    },
    {
      q: "What's a hash?",
      a: "Think of a hash as a digital fingerprint. Hashes are generated by mathematical functions that take any data and represent it as a fixed-size string of characters. Importantly, hashes are one-way only — you can quickly determine a given set of data's hash but cannot determine the data from the hash. Similar to how you cannot determine an identity from a fingerprint alone, you need the corresponding finger and person to compare it to. Comparing hashes is what allows Belrose to ensure that the records you provide have not been tampered with.",
    },
    {
      q: 'What is FHIR? Why do my records need to be in that format?',
      a: (
        <>
          <strong>FHIR</strong> (pronounced 'fire') stands for Fast Healthcare Interoperability
          Resources. It was developed by HL7 and is the global standard for exchanging healthcare
          information electronically. Without FHIR, medical records are trapped in silos — your
          cardiologist's software speaks one language, your GP's another. FHIR gives them a common
          alphabet and grammar. FHIR interoperability has been mandated by governments in the US,
          EU, UK, and Brazil.
        </>
      ),
    },
    {
      q: 'How do I know the FHIR conversion is accurate?',
      a: 'We use multiple validation layers including AI processing and optional clinician review. We also always recommend asking your GP if anything looks incomplete in your record.',
    },
    {
      q: 'Can Belrose see my data while it is being transformed into an interoperable format?',
      a: 'No. Our platform processes data in your browser before it ever reaches our servers. If manual review is needed to ensure the conversion is accurate, we would need to see it — but only with your explicit permission.',
    },
    {
      q: 'Since Belrose uses AI models to process data, can the major AI companies see our data?',
      a: 'We have zero-retention agreements signed with all of the AI labs we use to process data. We are also planning to run open-source models on our own infrastructure to give you the option of maximum privacy.',
    },
    {
      q: 'What is a distributed network?',
      a: 'A shared, digital ledger that records data securely, chronologically, and permanently across a decentralised network of thousands of computers around the world. This technology is commonly referred to as a blockchain, but that term carries a lot of baggage so we call it a distributed network.',
    },
    {
      q: 'Are there any special requirements for using the distributed network?',
      a: 'No. We take care of all of that on our end. You do not need to worry about any of the technical details — just enjoy the security it provides.',
    },
    {
      q: "What if there's a dispute about a record's authenticity?",
      a: "Our system is designed to handle this exact situation. Rather than a binary verified / not verified, our system calculates a credibility score for each record. Verifications increase the score, disputes decrease it. A dispute about a record's authenticity is recorded in our system and made visible to any future viewer of the record.",
    },
  ],

  'Privacy & Security': [
    {
      q: 'Can Belrose employees see my records?',
      a: (
        <>
          No. Your records are encrypted on your device before they ever reach our servers — a
          process called <strong>client-side encryption</strong>. This means even Belrose staff
          cannot read your data. We are designed from the ground up to not want your data in plain
          text.
        </>
      ),
      homepage: true,
    },
    {
      q: 'Where is my data stored?',
      a: 'You choose. We recommend our secure servers where you can access our sharing, editing, versioning, and other features. But you can store it anywhere you like — our protocol is storage-agnostic by design.',
    },
    {
      q: 'What happens if I lose my password?',
      a: 'Because your data is encrypted with a key only you hold, a lost password cannot be recovered the usual way. When you sign up, we give you a recovery phrase — keep it somewhere safe. This is the only way to restore access to your encrypted records.',
    },
    {
      q: 'Is Belrose HIPAA and GDPR compliant?',
      a: (
        <>
          Yes. Belrose is built from the ground up to comply with both <strong>HIPAA</strong> (US)
          and <strong>GDPR</strong> (UK/EU) standards. Because you own and control your data,
          Belrose operates as a data processor, not a data controller — giving you the strongest
          possible legal protections.
        </>
      ),
    },
    {
      q: 'What happens if I want to cancel my account?',
      a: 'You can export all your data at any time. If you decide to cancel, we provide a full export of your records in standard formats. After cancellation and export, your encrypted data is permanently deleted from our systems within 30 days.',
    },
    {
      q: 'What happens to our data if Belrose goes bankrupt?',
      a: 'Even if we go bankrupt, your records are protected. You legally own the data you store with our system. Even those with legal ownership of our company or physical access to our servers cannot access your records without your permission.',
    },
    {
      q: 'Could a government force Belrose to turn over my health data?',
      a: 'No. The data on our servers is client-side encrypted — even if government or law enforcement came to us with a warrant, we would be physically unable to provide anything other than scrambled cipher text.',
    },
  ],

  'Sharing & Permissions': [
    {
      q: 'How do I share records with my doctor?',
      a: 'You can share any record or set of records with a provider directly from the app. You control the permission level and can revoke access at any time.',
      homepage: true,
    },
    {
      q: 'Can I share records with someone who is not on Belrose?',
      a: 'Yes. You can share your record via email, text message, or any other method. We recommend the recipient creates a Belrose account to make full use of our functionality, but it is not required.',
    },
    {
      q: 'Can I manage records for a family member?',
      a: 'Yes. Belrose supports dependent accounts, so you can manage records for children, elderly parents, or anyone who has given you consent to do so.',
    },
  ],

  'For Providers & Healthcare Professionals': [
    {
      q: 'I received an email asking me to upload patient records. Is this legitimate?',
      a: (
        <>
          Yes. The email was sent because your patient submitted a formal{' '}
          <strong>Subject Access Request</strong> via Belrose Health. The patient is cc'd on the
          email as confirmation the request is genuine. Under <strong>GDPR Article 15</strong>{' '}
          (UK/EU) and <strong>HIPAA 45 CFR §164.524</strong> (US), covered entities are legally
          required to provide patients with a copy of their health records within 30 days of a
          written request. If you have any doubts, you can contact the patient directly — their
          email address is visible in the cc field of the email you received.
        </>
      ),
    },
    {
      q: 'Am I legally required to respond to a Belrose record request?',
      a: (
        <>
          Yes. A Belrose record request constitutes a formal written Subject Access Request under{' '}
          <strong>GDPR Article 15</strong> (UK/EU) and <strong>HIPAA 45 CFR §164.524</strong> (US).
          Covered entities are legally required to provide patients with access to their records
          within <strong>30 days</strong> of receipt. The ICO (UK) can take enforcement action
          against organisations that fail to comply, including issuing fines. You can read the full
          ICO guidance on subject access requests at{' '}
          <a
            href="https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/subject-access-requests/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-complement-1 underline underline-offset-2 hover:opacity-80"
          >
            ico.org.uk
          </a>
          .
        </>
      ),
    },
    {
      q: 'Can I redirect the patient to the NHS App or another channel instead?',
      a: (
        <>
          No. Under UK GDPR, patients have the right to nominate how and where they receive their
          records. The ICO's guidance is explicit that it is good practice to provide the response
          in the patient's preferred format and channel. A patient choosing to receive their records
          via Belrose is exercising a right the law grants them — you cannot substitute your
          preferred channel for theirs. You can read the ICO's guidance on supplying information in
          response to a SAR at{' '}
          <a
            href="https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/individual-rights/right-of-access/how-can-we-supply-information-to-the-requester/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-complement-1 underline underline-offset-2 hover:opacity-80"
          >
            ico.org.uk
          </a>
          .
        </>
      ),
    },
    {
      q: 'What format do I need to upload in?',
      a: 'Any format that is accurate and legible. PDF, Word document, scanned image, photograph of handwritten notes, CSV, FHIR JSON — whatever you have. Our platform accepts anything. You do not need to create new documents or transcribe existing ones.',
    },
    {
      q: 'Is the upload secure? Who can see what I upload?',
      a: (
        <>
          Your upload is encrypted in your browser before it leaves your device using the patient's
          cryptographic public key — a process called <strong>end-to-end encryption</strong>. Only
          the patient can decrypt and read the contents. Belrose cannot access the file at any
          point. No file data is stored unencrypted on our servers.
        </>
      ),
    },
    {
      q: 'What happens after I upload?',
      a: "The encrypted file is delivered directly to the patient's Belrose account. They are notified immediately. The request is marked fulfilled and the 30-day compliance deadline is met.",
    },
    {
      q: 'Does Belrose require access to our EHR system?',
      a: 'No. You can upload whatever you have — a PDF export, a printed scan, a photo of handwritten notes. We do offer EHR integrations for organisations that want them, but they are never required.',
    },
    {
      q: "Can Belrose records be imported back into our clinic's EHR?",
      a: 'Yes. We can build a two-way integration with any EHR system. Contact us at hello@belrosehealth.com for more information.',
    },
    {
      q: "Can Belrose integrate with our EHR's APIs to pull data directly?",
      a: 'Yes — that would be our preferred method. We recognise the complexity of such integrations and have built manual workarounds until they can be achieved at scale. Get in touch to discuss your specific system.',
    },
  ],

  'Data & Monetisation': [
    {
      q: 'Does Belrose earn money from my data?',
      a: "No. We cannot even see your data, so there's no way for us to sell it. We earn money by building services around your data for both you and your doctor. Our product is making your life healthier and more convenient.",
    },
    {
      q: 'Can I earn money from my health data?',
      a: 'Yes — if you choose to. Belrose enables you to opt into sharing anonymised data with researchers, pharmaceutical companies, or other organisations. You set the terms, you control who sees what, and any compensation flows directly to you. Participation is entirely voluntary.',
    },
    {
      q: 'How much can I earn?',
      a: (
        <>
          The honest answer is we do not know yet. We are still building this market and your data's
          value depends on its rarity, completeness, and which researchers are buying. What we can
          say is that this data is commercially valuable — Optum, which manages roughly half of UK
          GP records, generated <strong>$20 billion in analytics revenue</strong> alone last year.
          Patients contributed all of that value and received nothing. Belrose exists to change
          that. As our marketplace develops, we will publish transparent earnings data from real
          users.
        </>
      ),
    },
    {
      q: 'Who would buy my data?',
      a: 'Whoever you want. Potential buyers include pharmaceutical companies running clinical trials, academic researchers, public health agencies, and insurers building risk models. Your participation is entirely voluntary — no one sees your data unless you explicitly choose to share it.',
    },
    {
      q: 'Who owns my data on Belrose?',
      a: 'You do, completely. Belrose does not claim any rights to your data. We do not sell, share, or monetise your records — you do. This is the foundational principle the entire platform is built on.',
    },
  ],
};
