// src/components/site/FAQ/faqData.ts

/**
 * FAQ questions for site
 */

export interface FAQItem {
  q: string;
  a: string;
  homepage?: boolean;
}

type FAQData = Record<string, FAQItem[]>;

export const faqs: FAQData = {
  'Getting Started': [
    {
      q: 'What is Belrose and who is it for?',
      a: 'Belrose is a technology and incentivization infrastructure that gives people sovereignty over their health data. It is for anyone who wants to take control of their health data — whether you are managing a chronic condition, keeping track of family records, or simply want a complete picture of your health history in one place.',
      homepage: true,
    },
    {
      q: 'How is Belrose different from other health record apps?',
      a: "Other health record apps give you 'access' or a 'portal' to your records. Belrose gives you true ownership. Correct mistakes, manage access, donate your data, sell your data, all of this is possible with Belrose's data protocol.",
      homepage: true,
    },
    {
      q: 'Is Belrose free to use?',
      a: 'Managing your own records is free and always will be. We plan to offer premium features for those who want additional storage, data monetisation, and advanced health services.',
      homepage: true,
    },
    {
      q: 'How do I get my records into Belrose?',
      a: 'Under GDPR and HIPAA, you have a legal right to request your health records from any provider. Belrose helps you exercise that right automatically — we handle the requests and import your records once received. You can also upload documents manually.',
    },
    {
      q: 'What types of records can I store?',
      a: 'Anything! GP notes, hospital discharge summaries, lab results, imaging reports, prescriptions, vaccination records, dental records, and even self-reported data like fitness metrics or mental health journals.',
    },
    {
      q: 'What countries is Belrose available in?',
      a: 'While our main focus is currently the US and UK. Belrose is available to any person in any country that wants to manage their own health records.',
      homepage: true,
    },
  ],
  'The Belrose Protocol': [
    {
      q: 'What is the Belrose Protocol?',
      a: 'The Belrose Protocol is a record storage and management procedure we developed. It involves collecting a patients records, standardizing it into interoperable FHIR format, storing it on client-side encrypted servers, sharing it as desired, and using a distributed network to store hashes for verification. ',
      homepage: true,
    },
    {
      q: 'How can a doctor or third party rely on a record that is completely controlled by the patient? The patient could be lying.',
      a: 'Our protocol involves storing hashes of the record data on a distributed network alongside verifications from trusted parties. This allows future viewers of patient-provided records to know that the record has not been tampered with.',
    },
    {
      q: "What's a hash?",
      a: "Think of a hash as a digital fingerprint. Hashes are generated by mathematical functions that take any data and represent it as a fixed-size string of characters. Importantly, hashes are one-way only, you can quickly determine a given set of data's hash but cannot determine the data from the hash. Similar to how you cannot determine an identity from a fingerprint alone, you need the corresponding finger to compare it to. Comparing hashes is what allows Belrose to ensure that the records you provide have not been tampered with.",
    },
    {
      q: 'What is FHIR? Why do my records need to be in that format?',
      a: "FHIR (pronounced 'fire') stands for Fast Healthcare Interoperability Resources. FHIR was developed by an organization called HL7 and is the standard for exchanging healthcare information electronically. Without FHIR, medical records are trapped in silos, your cardiologist's software speaks one language, your GPs another. FHIR was created to give them all a common alphabet and grammar. FHIR interoperability has been mandated by governments in the US, EU, UK, and Brazil for example.",
    },
    {
      q: 'How do I know the FHIR conversion is accurate?',
      a: 'We use multiple validation layers including LLM processing and optional clinician review. Also, we always recommend you ask your GP if anything is missing from your record!',
    },
    {
      q: 'Can Belrose see my data while its being transformed into an interoperable format?',
      a: 'No, our platform can process data in your browser before ever uploading it to our servers. However, if manual review is needed to ensure the conversion is accurate then we would need to see it. But that would only happen with your explicit permission.',
    },
    {
      q: 'Since Belrose is using AI models to process data, can the major AI companies see our data?',
      a: 'We have zero-retention agreements signed with all of the AI labs we use to process data. But you are right to be concerned, because we have no real way to verify they are not retaining data. That is why we are planning to run open source models on our own to give you the option of maximum privacy.',
    },
    {
      q: 'What is a distributed network?',
      a: 'When we say distributed network, we are refering to a shared, digital ledger that records data securely, chronologically, and permanently across a decentralized network of computers. This technology is commonly referred to as a blockchain. But that term has a lot of baggage so we stick to calling it a distributed network.',
    },
    {
      q: 'Are there any special requirements for using the distributed network?',
      a: 'No. We take care of all of that on our end. You do not need to worry about any of details of managing a distributed network, just enjoy the security it provides.',
    },
    {
      q: "What if there's a dispute about a record's authenticity?",
      a: "Our system is designed to handle this exact situation. Rather than a binary verified or not verified, our system calculates a credibility score for each record. Verifications increase the score, disputes decrease the score. If there's a dispute about a record's authenticity that can be recorded in our system and made known to any future viewer of the record.",
    },
  ],
  'Privacy & Security': [
    {
      q: 'Can Belrose employees see my records?',
      a: 'No. Your records are encrypted on your device before they ever reach our servers — a process called client-side encryption. This means even Belrose staff cannot read your data. We are the only health tech company that does not want your data (in plain text format).',
      homepage: true,
    },
    {
      q: 'Where is my data stored?',
      a: 'You choose. We recommend our secure servers where you can access our sharing, editing, versioning, and other features. But you can store it in an email chain to your doctor, a text message with your mom, on your phone, or with a third-party provider of your choice. Our protocol is storage-agnostic by design.',
    },
    {
      q: 'What happens if I lose my password?',
      a: 'Because your data is encrypted with a key only you hold, a lost password cannot be recovered by resetting it the usual way. When you sign up, we give you a 24-word recovery phrase — keep it somewhere safe. This is the only way to restore access to your encrypted records.',
    },
    {
      q: 'Is Belrose HIPAA and GDPR compliant?',
      a: 'Yes. Belrose is built from the ground up to comply with both HIPAA (US) and GDPR (UK/EU) standards. Because you own and control your data, Belrose operates as a data processor, not a data controller — giving you the strongest possible legal protections.',
    },
    {
      q: 'What happens if I want to cancel my account?',
      a: 'You can export all your data at any time. If you decide to cancel your account, we provide a full export of your records in standard formats. After cancellation and export, your encrypted data, which we can not read regardless, is permanently deleted from our systems within 30 days.',
    },
    {
      q: 'What happens to our data if Belrose goes bankrupt?',
      a: 'Even if we go bankrupt, your records are protected. You legally own the data you store with our system. Even those with legal ownership of our company or physical access to servers will not be able access to your records unless you allow them to.',
    },
    {
      q: 'Could a government force Belrose to turn over my health data?',
      a: 'No, because the data on our servers is client-side encrypted, even if government or law enforcement came to us with a warrant for your data, we would physically be unable to provide anything besides scrambled cipher text.',
    },
  ],
  'Sharing & Permissions': [
    {
      q: 'How do I share records with my doctor?',
      a: 'You can share any record or set of records with a provider directly from the app. You control the permission level and you can revoke access at any time.',
      homepage: true,
    },
    {
      q: 'Can I share records with someone who is not on Belrose?',
      a: 'Yes. Although we would recommend they create a Belrose account to make full use of our functionality, you can share your record via email, text message, fax, you could even theoretically write your records by hand and send it to them. All while still benefiting from our transformation and verification features.',
    },
    {
      q: 'Can I manage records for a family member?',
      a: 'Yes. Belrose supports dependent accounts, so you can manage records for children, elderly parents, or anyone who has given you consent to do so.',
    },
  ],
  'For Providers & Healthcare Professionals': [
    {
      q: 'Does Belrose require access or integration with EHRs?',
      a: "No. We can accept any version of a patient's health records that you are willing to verify as your work. PDFs, photos, images anything works as long as it is legible, legitimate health record.",
    },
    {
      q: "Can Belrose records be reuploaded into my clinic's EHR?",
      a: 'Yes we can build a two way integration back into any EHR system. Contact our sales team for more information!',
    },
    {
      q: "Can Belrose integrate with my EHR's APIs to pull data?",
      a: 'Yes, in fact that would be our ideal method of receiving health data. But we recognize the difficulty of such integrations and have built work arounds until such integration can be achieved at scale.',
    },
  ],
  'Data & Monetisation': [
    {
      q: 'Does Belrose earn money from my data?',
      a: "No. We cannot even see your data, so there's no way for us to sell it. We earn money by building services around your data for both you and your doctor. Our product is making your life healthier and more convenient.",
    },
    {
      q: 'Can I earn money from my health data?',
      a: 'Yes — if you choose to. Belrose enables you to opt into sharing anonymised data with researchers, pharmaceutical companies, or other organisations. You set the terms, you control who sees what, and any compensation flows directly to you. Participation is entirely voluntary.',
    },
    {
      q: 'How much can I earn?',
      a: "The honest answer is we don't know yet. We are still building this market and your data's value depends on its rarity, completeness, and which researchers are buying. What we can say is that this data is commercially valuable — Optum, which manages roughly half of UK GP records, generated $20 billion in analytics revenue alone last year. Patients contributed all of that value and received nothing. Belrose exists to change that. As our marketplace develops, we will publish transparent earnings data from real users. ",
    },
    {
      q: 'Who would buy my data?',
      a: 'Whoever you want. Potential buyers could be pharmaceutical companies running clinical trials, academic researchers conducting studies, public health agencies, insurance building risk models. But its important to remember your participation is entirely voluntary, no one sees your data unless you want them to.',
    },
    {
      q: 'Who owns my data on Belrose?',
      a: 'You do, completely. Belrose does not claim any rights to your data. We do not sell, share, or monetise your records, you do. This is the foundational principle the entire platform is built on.',
    },
  ],
};
