/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { HealthRecordCore__factory } from "./HealthRecordCore__factory";
export { MemberRoleManagerInterface__factory } from "./MemberRoleManagerInterface__factory";
