"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.HealthRecordCoreInterface__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "bytes32",
                name: "recordIdHash",
                type: "bytes32",
            },
            {
                internalType: "bytes32",
                name: "userIdHash",
                type: "bytes32",
            },
        ],
        name: "isActiveSubject",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
class HealthRecordCoreInterface__factory {
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.HealthRecordCoreInterface__factory = HealthRecordCoreInterface__factory;
HealthRecordCoreInterface__factory.abi = _abi;
//# sourceMappingURL=HealthRecordCoreInterface__factory.js.map