"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MemberRoleManagerInterface__factory = exports.MemberRoleManager__factory = exports.HealthRecordCoreInterface__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var HealthRecordCoreInterface__factory_1 = require("./HealthRecordCoreInterface__factory");
Object.defineProperty(exports, "HealthRecordCoreInterface__factory", { enumerable: true, get: function () { return HealthRecordCoreInterface__factory_1.HealthRecordCoreInterface__factory; } });
var MemberRoleManager__factory_1 = require("./MemberRoleManager__factory");
Object.defineProperty(exports, "MemberRoleManager__factory", { enumerable: true, get: function () { return MemberRoleManager__factory_1.MemberRoleManager__factory; } });
var MemberRoleManagerInterface__factory_1 = require("./MemberRoleManagerInterface__factory");
Object.defineProperty(exports, "MemberRoleManagerInterface__factory", { enumerable: true, get: function () { return MemberRoleManagerInterface__factory_1.MemberRoleManagerInterface__factory; } });
//# sourceMappingURL=index.js.map