// functions/src/types/index.ts

import { Timestamp } from 'firebase-admin/firestore';

// ==================== ERROR TYPES ====================

export class CloudFunctionError extends Error {
  constructor(
    message: string,
    public code: string,
    public statusCode: number = 500
  ) {
    super(message);
    this.name = 'CloudFunctionError';
  }
}

export type ErrorCode =
  | 'INVALID_REQUEST'
  | 'MISSING_DATA'
  | 'CLAUDE_API_ERROR'
  | 'PROCESSING_FAILED'
  | 'VALIDATION_ERROR'
  | 'UNKNOWN_ERROR';

//types/api.types.ts
// Types shared between frontend and backend, usually representing API contract

/**
 * ============================================================================
 * IMAGE ANALYSIS API
 * ============================================================================
 */

export const SUPPORTED_IMAGE_TYPES = [
  'image/jpeg',
  'image/jpg',
  'image/png',
  'image/gif',
  'image/webp',
] as const;

export type SupportedImageType = (typeof SUPPORTED_IMAGE_TYPES)[number];

export interface ImageData {
  base64: string;
  mediaType: SupportedImageType;
}

export type AnalysisType = 'detection' | 'extraction' | 'full';

/**
 * Request payload for image analysis API
 * POST /analyzeImageWithAI
 */
export interface ImageAnalysisRequest {
  image: ImageData;
  fileName?: string;
  fileType?: string;
  analysisType?: AnalysisType;
}

/**
 * Response payload from image analysis API
 * POST /analyzeImageWithAI
 */
export interface ImageAnalysisResponse {
  /** Whether the image appears to be medical-related */
  isMedical?: boolean;
  /** Confidence score (0-1) */
  confidence?: number;
  /** AI reasoning for the classification */
  reasoning?: string;
  suggestion?: string;
  extractedText?: string;
  medicalSpecialty?: string | null;
  structuredData?: MedicalStructuredData;
  imageQuality?: 'excellent' | 'good' | 'fair' | 'poor';
  /** Readability score (0-100) */
  readabilityScore?: number;
  analyzedAt?: string;
  fileName?: string;
  fileType?: string;
  analysisType?: string;
}

/**
 * Structured medical data that can be extracted from images
 */
export interface MedicalStructuredData {
  patientName?: string | null;
  patientId?: string | null;
  date?: string | null;
  provider?: string | null;
  facility?: string | null;
  testResults?: MedicalTestResult[] | null;
  medications?: string[] | null;
  diagnoses?: string[] | null;
}

/**
 * Medical test result extracted from an image
 */
export interface MedicalTestResult {
  testName?: string;
  value?: string;
  unit?: string;
  normalRange?: string;
  abnormal?: boolean;
}

/**
 * ============================================================================
 * FHIR CONVERSION API
 * ============================================================================
 */

/**
 * Request payload for FHIR conversion API
 */
export interface FHIRConversionRequest {
  documentText: string;
  fileName?: string;
  fileType?: string;
}

/**
 * Response payload from FHIR conversion API. POST /convertToFHIR
 */
export interface FHIRConversionResponse {
  resourceType: 'Bundle';
  entry: Array<{
    resource: any; // Generic FHIR resource
  }>;
  [key: string]: any;
}

/**
 * ============================================================================
 * Record Processing
 * ============================================================================
 */

/**
 * Request payload for Belrose Fields processing
 */
export interface BelroseFieldProcessingRequest {
  fhirData: any;
  extractedText?: string;
  originalText?: string;
  fileName?: string;
  analysis?: FHIRAnalysis;
  contextText?: string;
}

export interface FHIRAnalysis {
  resourceTypes: string[];
  observations: any[];
  encounters: any[];
  diagnosticReports: any[];
  practitioners: any[];
  organizations: any[];
  patients: any[];
  extractedDates: string[];
}
// ==================== HEALTH RECORDS FILE ====================

//Base Belrose Fields generated by createBelroseFields Coud function
export interface BelroseFields {
  visitType: string; // e.g., "Follow-up Appointment", "Lab Results", "Imaging Study"
  title: string; // Short descriptive title (e.g., "Cardiology Follow-up")
  summary: string; // Tweet-length summary, main information a future reader would need to know
  completedDate: string; // ISO date string - the main date for this record
  provider: string; // Primary provider name
  institution: string; // Healthcare institution/facility
  patient: string; // Patient Name
  detailedNarrative?: string; //detailed information on the medical interaction. derived from FHIR, but human readable
}

export interface RoleInitialization {
  blockchainInitialized: boolean;
  blockchainInitializedAt: Timestamp;
  blockchainInitTxHash: string;
  blockchainInitBlockNumber: number;
  syncedFromChain: boolean; //For when an intialization had to be self-healed. Indicates there was an issue with updating firebase previously for future debugging/auditing
}

export interface CredibilityScore {
  score: number; //0-1000
  lastUpdated: Timestamp;
}

export type AIProcessingStatus =
  | 'pending' // AI processing not yet started
  | 'processing' // AI is currently processing
  | 'completed' // AI processing finished successfully
  | 'failed' // AI processing failed
  | 'not_needed'; // This record type doesn't need AI processing

export type FileStatus =
  | 'open' //waiting to upload
  | 'pending' // File uploaded, waiting to process
  | 'processing' // Currently being processed
  | 'uploading' // Currently uploading, use for making sure there aren't multiple uploads
  | 'completed' // Successfully processed
  | 'error'; // Failed with error

export type SourceType =
  | 'Plain Text Submission'
  | 'Manual FHIR JSON Submission'
  | 'File Upload'
  | 'Belrose Identity Form';

//Processing Stages good for the progress chips in the Add Record process
export type ProcessingStages =
  | 'Starting processing...'
  | 'Extracting text...'
  | 'Text extraction completed'
  | 'Converting to FHIR...'
  | 'FHIR conversion completed'
  | 'Completing...'
  | 'AI processing...'
  | 'AI analyzing content...'
  | 'Encrypting record data...'
  | 'Record encrypted'
  | 'Generating record hash...'
  | 'Uploading...'
  | undefined;

export interface VirtualFileInput {
  fileName?: string;
  sourceType?: SourceType;
  extractedText?: string;
  fhirData?: any;
  wordCount?: number;
  [key: string]: any;
}

export interface FileObject {
  // === CORE IDENTIFICATION, (EXCLUDES FILE NAME, IN ENCRYPTED HEALTH DATA SECTION BELOW) ===
  id: string; //fileId. Generated in useFileManager via createFileObject() or addVirtualFile(). file_${Date.now()}_${Math.random().toString(36).substr(2, 9)}
  firestoreId?: string; //Id for firestore set after upload

  // === FILE PROPERTIES (EXCLUDES FILE, IN ENCRYPTED HEALTH DATA SECTION BELOW)===
  fileSize: number; //file size. Set in createFileObject in useFileManager.ts. file.size for real files
  fileType: string; //file type. Set in createFileObject in useFileManager.ts. file.type for real files or application/fhir+json for virtual - NEVER undefined
  wordCount?: number; //calculated during text extraction

  // === OWNERSHIP AND PERMISSIONS ===
  uploadedBy?: string; // User ID of who created/uploaded the record (for audit trail)
  owners?: string[]; // Array of user IDs with ultimate ownership access to record (read, update, delete, share)
  administrators: string[]; //Array of userIDs with administrative access to records, can't remove others
  viewers?: string[]; // Array of user IDs with view access to record
  subjects?: string[]; //The subject of this record. Made it an array for edge cases where there are multiple subjects (couples therapy, mother/newborn, family history, genetic testing)
  trustees?: string[]; // userIds who have access via an active trustee relationship

  // === PROCESSING STATUS ===
  status: FileStatus; //Processing property. Initially set as pending. Then pending/processing... see below
  error?: string; //Failed processing
  aiProcessingStatus?: AIProcessingStatus; //For Belrose Fields
  processingStage?: ProcessingStages;
  uploadInProgress?: boolean; // for managing upload process

  // === VERIFICATION AND SECURITY ===
  originalFileHash?: string | null; //hash of the original file that was uploaded
  recordHash?: string | null; //hash of the record content
  previousRecordHash?: string[] | null; //to establish chain of records in case they are edited
  blockchainRoleInitialization?: RoleInitialization;
  credibility?: CredibilityScore;

  // === METADATA ===
  sourceType?: SourceType;
  isVirtual?: boolean; //for virtual files
  downloadURL?: string;
  storagePath?: string;
  versionNumber?: string;

  // === TIMESTAMPS ===
  uploadedAt?: Timestamp;
  createdAt?: Timestamp;
  lastModified?: Timestamp; //Filetracking for UI state management.

  // PLAIN TEXT PERSONAL HEALTH DATA, MUST BE ENCRYPTED
  fileName: string; //file name or custom name for virtual files. set by createFileObject() in useFileManager.ts
  file?: File; //actual file object from file input. Real life upload not virtual. Generated in createFileObject in useFileManager.ts
  extractedText?: string | null; //text extracted from image/pdf
  originalText?: string | null; //text typed into app by user
  contextText?: string | null; //context provided along with either the file upload or fhir upload
  fhirData?: any;
  belroseFields?: BelroseFields; //AI enriched fields for easy labeling within the Belrose App
  customData?: any; //for non-medical data that may come in different formats, but not be particularly suited to FHIR format

  // Individual encrypted fields (as stored in Firestore)
  encryptedFileName?: { encrypted: string; iv: string };
  encryptedExtractedText?: { encrypted: string; iv: string };
  encryptedOriginalText?: { encrypted: string; iv: string };
  encryptedContextText?: { encrypted: string; iv: string };
  encryptedFhirData?: { encrypted: string; iv: string };
  encryptedBelroseFields?: { encrypted: string; iv: string };
  encryptedCustomData?: { encrypted: string; iv: string };

  // Encryption fields at ROOT level (as stored in Firestore)
  isEncrypted?: boolean;
  encryptedFileIV?: string; // IV for the file stored in Firebase Storage

  //Used during processing, ArrayBuffers are in memory. But roo-level encrypted Fiels are for retrieval in Firestore
  encryptedData?: {
    encryptedKey: string; // Single key for all encrypted data (Base64)

    // Encrypted fileName (always exists - contains PII!)
    fileName: {
      encrypted: ArrayBuffer; // Only exists during upload process
      iv: string; // Base64
    };

    // Encrypted file (original upload) - stored in memory during processing
    file?: {
      encrypted: ArrayBuffer; // Only exists during upload process
      iv: string; // Base64
    };

    // Encrypted extracted text
    extractedText?: {
      encrypted: ArrayBuffer; // Only exists during upload process
      iv: string; // Base64
    };

    // Encrypted original text (if exists)
    originalText?: {
      encrypted: ArrayBuffer; // Only exists during upload process
      iv: string; // Base64
    };

    // Encrypted context text (if exists)
    contextText?: {
      encrypted: ArrayBuffer; // Only exists during upload process
      iv: string; // Base64
    };

    // Encrypted FHIR data (if exists)
    fhirData?: {
      encrypted: ArrayBuffer; // Only exists during upload process
      iv: string; // Base64
    };

    // Encrypted belrose fields (if exists)
    belroseFields?: {
      encrypted: ArrayBuffer; // Only exists during upload process
      iv: string; // Base64
    };

    // Encrypted custom data (if exists)
    customData?: {
      encrypted: ArrayBuffer; // Only exists during upload process
      iv: string; // Base64
    };
  };
}

export interface RecordReviewStatus {
  // ── Verification ────────────────────────────────────────────────────────────
  hasVerification: boolean;
  verificationIsCurrentHash: boolean; // false if verified against an older hash
  verificationLevel?: VerificationLevelOptions;

  // ── Dispute ─────────────────────────────────────────────────────────────────
  hasDispute: boolean;
  disputeIsCurrentHash: boolean; // false if disputed against an older hash
  disputeSeverity?: DisputeSeverityOptions;

  // ── Reaction ─────────────────────────────────────────────────────────────────
  // A reaction is tied to a specific dispute, so staleness is inherited:
  // if the dispute it was made against is stale, the reaction is stale too.
  hasReaction: boolean;
  reactionIsCurrentHash: boolean;
  reactionSupportsDispute?: boolean; // true = supported, false = opposed

  // ── Derived convenience flags ────────────────────────────────────────────────
  hasAnyActiveReview: boolean; // any of the three is active
  hasStaleReview: boolean; // any review exists but against an old hash
  currentHashReviewed: boolean; // at least one review is against current hash
}

export type VerificationLevelOptions = 1 | 2 | 3;
export type DisputeSeverityOptions = 1 | 2 | 3;
