/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  HealthRecordCoreInterface,
  HealthRecordCoreInterfaceInterface,
} from "../../../smartContracts/MemberRoleManager.sol/HealthRecordCoreInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "recordIdHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "userIdHash",
        type: "bytes32",
      },
    ],
    name: "isActiveSubject",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class HealthRecordCoreInterface__factory {
  static readonly abi = _abi;
  static createInterface(): HealthRecordCoreInterfaceInterface {
    return new Interface(_abi) as HealthRecordCoreInterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): HealthRecordCoreInterface {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as HealthRecordCoreInterface;
  }
}
