"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MemberRoleManagerInterface__factory = exports.HealthRecordCore__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var HealthRecordCore__factory_1 = require("./HealthRecordCore__factory");
Object.defineProperty(exports, "HealthRecordCore__factory", { enumerable: true, get: function () { return HealthRecordCore__factory_1.HealthRecordCore__factory; } });
var MemberRoleManagerInterface__factory_1 = require("./MemberRoleManagerInterface__factory");
Object.defineProperty(exports, "MemberRoleManagerInterface__factory", { enumerable: true, get: function () { return MemberRoleManagerInterface__factory_1.MemberRoleManagerInterface__factory; } });
//# sourceMappingURL=index.js.map