/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace HealthRecordCore {
  export type DisputeStruct = {
    disputerIdHash: BytesLike;
    recordIdHash: BytesLike;
    severity: BigNumberish;
    culpability: BigNumberish;
    notes: string;
    createdAt: BigNumberish;
    isActive: boolean;
  };

  export type DisputeStructOutput = [
    disputerIdHash: string,
    recordIdHash: string,
    severity: bigint,
    culpability: bigint,
    notes: string,
    createdAt: bigint,
    isActive: boolean
  ] & {
    disputerIdHash: string;
    recordIdHash: string;
    severity: bigint;
    culpability: bigint;
    notes: string;
    createdAt: bigint;
    isActive: boolean;
  };

  export type UnacceptedFlagStruct = {
    recordIdHash: BytesLike;
    reporterIdHash: BytesLike;
    recordHash: BytesLike;
    createdAt: BigNumberish;
    isActive: boolean;
  };

  export type UnacceptedFlagStructOutput = [
    recordIdHash: string,
    reporterIdHash: string,
    recordHash: string,
    createdAt: bigint,
    isActive: boolean
  ] & {
    recordIdHash: string;
    reporterIdHash: string;
    recordHash: string;
    createdAt: bigint;
    isActive: boolean;
  };

  export type VerificationStruct = {
    verifierIdHash: BytesLike;
    recordIdHash: BytesLike;
    level: BigNumberish;
    createdAt: BigNumberish;
    isActive: boolean;
  };

  export type VerificationStructOutput = [
    verifierIdHash: string,
    recordIdHash: string,
    level: bigint,
    createdAt: bigint,
    isActive: boolean
  ] & {
    verifierIdHash: string;
    recordIdHash: string;
    level: bigint;
    createdAt: bigint;
    isActive: boolean;
  };
}

export interface HealthRecordCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "activeUnacceptedFlagCount"
      | "addRecordHash"
      | "admin"
      | "anchorRecord"
      | "currentlyDisputed"
      | "currentlyVerified"
      | "disputeIndex"
      | "disputeRecord"
      | "disputes"
      | "disputesByUser"
      | "doesHashExist"
      | "flagUnacceptedUpdate"
      | "getActiveRecordSubjects"
      | "getActiveUnacceptedFlagCount"
      | "getDisputeStats"
      | "getDisputes"
      | "getRecordIdForHash"
      | "getRecordSubjects"
      | "getRecordVersionHistory"
      | "getSubjectMedicalHistory"
      | "getSubjectStats"
      | "getTotalAnchoredRecords"
      | "getUnacceptedFlag"
      | "getUnacceptedFlags"
      | "getUserDispute"
      | "getUserDisputes"
      | "getUserVerification"
      | "getUserVerifications"
      | "getVerificationStats"
      | "getVerifications"
      | "getVersionCount"
      | "hasActiveUnacceptedFlags"
      | "hasUserDisputed"
      | "hasUserVerified"
      | "initialize"
      | "isActiveSubject"
      | "isHashActive"
      | "isSubject"
      | "isSubjectActive"
      | "isSubjectOfRecord"
      | "memberRoleManager"
      | "modifyDispute"
      | "modifyVerificationLevel"
      | "proxiableUUID"
      | "reanchorRecord"
      | "recordIdForHash"
      | "recordSubjects"
      | "recordVersionHistory"
      | "retractDispute"
      | "retractRecordHash"
      | "retractVerification"
      | "revokeUnacceptedFlag"
      | "setMemberRoleManager"
      | "subjectMedicalHistory"
      | "totalAnchoredRecords"
      | "totalDisputes"
      | "totalUnacceptedFlags"
      | "totalVerifications"
      | "transferAdmin"
      | "unacceptedFlagIndex"
      | "unacceptedFlagsBySubject"
      | "unanchorRecord"
      | "upgradeToAndCall"
      | "verificationIndex"
      | "verifications"
      | "verificationsByUser"
      | "verifyRecord"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminTransferred"
      | "DisputeModification"
      | "DisputeRetracted"
      | "Initialized"
      | "RecordAnchored"
      | "RecordDisputed"
      | "RecordHashAdded"
      | "RecordHashRetracted"
      | "RecordReanchored"
      | "RecordUnanchored"
      | "RecordVerified"
      | "UnacceptedUpdateFlagRevoked"
      | "UnacceptedUpdateFlagged"
      | "Upgraded"
      | "VerificationLevelModified"
      | "VerificationRetracted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeUnacceptedFlagCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addRecordHash",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "anchorRecord",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentlyDisputed",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentlyVerified",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeIndex",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeRecord",
    values: [BytesLike, BytesLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "disputes",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputesByUser",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "doesHashExist",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "flagUnacceptedUpdate",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveRecordSubjects",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveUnacceptedFlagCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDisputeStats",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDisputes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordIdForHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordSubjects",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordVersionHistory",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubjectMedicalHistory",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubjectStats",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalAnchoredRecords",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUnacceptedFlag",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUnacceptedFlags",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserDispute",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserDisputes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserVerification",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserVerifications",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerificationStats",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifications",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVersionCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasActiveUnacceptedFlags",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasUserDisputed",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasUserVerified",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isActiveSubject",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isHashActive",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSubject",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSubjectActive",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSubjectOfRecord",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "memberRoleManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "modifyDispute",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "modifyVerificationLevel",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reanchorRecord",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordIdForHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordSubjects",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordVersionHistory",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "retractDispute",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "retractRecordHash",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "retractVerification",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeUnacceptedFlag",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMemberRoleManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subjectMedicalHistory",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAnchoredRecords",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalDisputes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalUnacceptedFlags",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVerifications",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unacceptedFlagIndex",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unacceptedFlagsBySubject",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unanchorRecord",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationIndex",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifications",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationsByUser",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyRecord",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeUnacceptedFlagCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addRecordHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "anchorRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentlyDisputed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentlyVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disputes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disputesByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "doesHashExist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "flagUnacceptedUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveRecordSubjects",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveUnacceptedFlagCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDisputeStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDisputes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordIdForHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordSubjects",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordVersionHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubjectMedicalHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubjectStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalAnchoredRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnacceptedFlag",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnacceptedFlags",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserDisputes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserVerifications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerificationStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerifications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVersionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasActiveUnacceptedFlags",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasUserDisputed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasUserVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isActiveSubject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isHashActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isSubject", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isSubjectActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSubjectOfRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "memberRoleManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "modifyDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "modifyVerificationLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reanchorRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordIdForHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordSubjects",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordVersionHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retractDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retractRecordHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retractVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeUnacceptedFlag",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMemberRoleManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subjectMedicalHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAnchoredRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDisputes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalUnacceptedFlags",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVerifications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unacceptedFlagIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unacceptedFlagsBySubject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unanchorRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationsByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyRecord",
    data: BytesLike
  ): Result;
}

export namespace AdminTransferredEvent {
  export type InputTuple = [
    oldAdmin: AddressLike,
    newAdmin: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    oldAdmin: string,
    newAdmin: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    oldAdmin: string;
    newAdmin: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeModificationEvent {
  export type InputTuple = [
    recordHash: BytesLike,
    disputerIdHash: BytesLike,
    oldSeverity: BigNumberish,
    newSeverity: BigNumberish,
    oldCulpability: BigNumberish,
    newCulpability: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordHash: string,
    disputerIdHash: string,
    oldSeverity: bigint,
    newSeverity: bigint,
    oldCulpability: bigint,
    newCulpability: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordHash: string;
    disputerIdHash: string;
    oldSeverity: bigint;
    newSeverity: bigint;
    oldCulpability: bigint;
    newCulpability: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeRetractedEvent {
  export type InputTuple = [
    recordHash: BytesLike,
    disputerIdHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordHash: string,
    disputerIdHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordHash: string;
    disputerIdHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordAnchoredEvent {
  export type InputTuple = [
    recordIdHash: BytesLike,
    recordHash: BytesLike,
    subjectIdHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordIdHash: string,
    recordHash: string,
    subjectIdHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordIdHash: string;
    recordHash: string;
    subjectIdHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordDisputedEvent {
  export type InputTuple = [
    recordHash: BytesLike,
    recordIdHash: BytesLike,
    disputerIdHash: BytesLike,
    severity: BigNumberish,
    culpability: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordHash: string,
    recordIdHash: string,
    disputerIdHash: string,
    severity: bigint,
    culpability: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordHash: string;
    recordIdHash: string;
    disputerIdHash: string;
    severity: bigint;
    culpability: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordHashAddedEvent {
  export type InputTuple = [
    recordIdHash: BytesLike,
    newHash: BytesLike,
    addedBy: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordIdHash: string,
    newHash: string,
    addedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordIdHash: string;
    newHash: string;
    addedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordHashRetractedEvent {
  export type InputTuple = [
    recordIdHash: BytesLike,
    recordHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordIdHash: string,
    recordHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordIdHash: string;
    recordHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordReanchoredEvent {
  export type InputTuple = [
    recordIdHash: BytesLike,
    subjectIdHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordIdHash: string,
    subjectIdHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordIdHash: string;
    subjectIdHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordUnanchoredEvent {
  export type InputTuple = [
    recordIdHash: BytesLike,
    subjectIdHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordIdHash: string,
    subjectIdHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordIdHash: string;
    subjectIdHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordVerifiedEvent {
  export type InputTuple = [
    recordHash: BytesLike,
    recordIdHash: BytesLike,
    verifierIdHash: BytesLike,
    level: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordHash: string,
    recordIdHash: string,
    verifierIdHash: string,
    level: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordHash: string;
    recordIdHash: string;
    verifierIdHash: string;
    level: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnacceptedUpdateFlagRevokedEvent {
  export type InputTuple = [
    subjectIdHash: BytesLike,
    recordIdHash: BytesLike,
    reporterIdHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    subjectIdHash: string,
    recordIdHash: string,
    reporterIdHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    subjectIdHash: string;
    recordIdHash: string;
    reporterIdHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnacceptedUpdateFlaggedEvent {
  export type InputTuple = [
    subjectIdHash: BytesLike,
    recordIdHash: BytesLike,
    reporterIdHash: BytesLike,
    recordHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    subjectIdHash: string,
    recordIdHash: string,
    reporterIdHash: string,
    recordHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    subjectIdHash: string;
    recordIdHash: string;
    reporterIdHash: string;
    recordHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationLevelModifiedEvent {
  export type InputTuple = [
    recordHash: BytesLike,
    verifierIdHash: BytesLike,
    oldLevel: BigNumberish,
    newLevel: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordHash: string,
    verifierIdHash: string,
    oldLevel: bigint,
    newLevel: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordHash: string;
    verifierIdHash: string;
    oldLevel: bigint;
    newLevel: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationRetractedEvent {
  export type InputTuple = [
    recordHash: BytesLike,
    verifierIdHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordHash: string,
    verifierIdHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordHash: string;
    verifierIdHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HealthRecordCore extends BaseContract {
  connect(runner?: ContractRunner | null): HealthRecordCore;
  waitForDeployment(): Promise<this>;

  interface: HealthRecordCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  activeUnacceptedFlagCount: TypedContractMethod<
    [arg0: BytesLike],
    [bigint],
    "view"
  >;

  addRecordHash: TypedContractMethod<
    [recordIdHash: BytesLike, newHash: BytesLike],
    [void],
    "nonpayable"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  anchorRecord: TypedContractMethod<
    [recordIdHash: BytesLike, recordHash: BytesLike, subjectIdHash: BytesLike],
    [void],
    "nonpayable"
  >;

  currentlyDisputed: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [boolean],
    "view"
  >;

  currentlyVerified: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [boolean],
    "view"
  >;

  disputeIndex: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [bigint],
    "view"
  >;

  disputeRecord: TypedContractMethod<
    [
      recordIdHash: BytesLike,
      recordHash: BytesLike,
      severity: BigNumberish,
      culpability: BigNumberish,
      notes: string
    ],
    [void],
    "nonpayable"
  >;

  disputes: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint, string, bigint, boolean] & {
        disputerIdHash: string;
        recordIdHash: string;
        severity: bigint;
        culpability: bigint;
        notes: string;
        createdAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  disputesByUser: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  doesHashExist: TypedContractMethod<
    [recordHash: BytesLike],
    [boolean],
    "view"
  >;

  flagUnacceptedUpdate: TypedContractMethod<
    [
      subjectIdHash: BytesLike,
      recordIdHash: BytesLike,
      reporterIdHash: BytesLike,
      recordHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getActiveRecordSubjects: TypedContractMethod<
    [recordIdHash: BytesLike],
    [string[]],
    "view"
  >;

  getActiveUnacceptedFlagCount: TypedContractMethod<
    [subjectIdHash: BytesLike],
    [bigint],
    "view"
  >;

  getDisputeStats: TypedContractMethod<
    [recordHash: BytesLike],
    [[bigint, bigint] & { total: bigint; active: bigint }],
    "view"
  >;

  getDisputes: TypedContractMethod<
    [recordHash: BytesLike],
    [HealthRecordCore.DisputeStructOutput[]],
    "view"
  >;

  getRecordIdForHash: TypedContractMethod<
    [recordHash: BytesLike],
    [string],
    "view"
  >;

  getRecordSubjects: TypedContractMethod<
    [recordIdHash: BytesLike],
    [string[]],
    "view"
  >;

  getRecordVersionHistory: TypedContractMethod<
    [recordIdHash: BytesLike],
    [string[]],
    "view"
  >;

  getSubjectMedicalHistory: TypedContractMethod<
    [userIdHash: BytesLike],
    [string[]],
    "view"
  >;

  getSubjectStats: TypedContractMethod<
    [recordIdHash: BytesLike],
    [[bigint, bigint] & { total: bigint; active: bigint }],
    "view"
  >;

  getTotalAnchoredRecords: TypedContractMethod<[], [bigint], "view">;

  getUnacceptedFlag: TypedContractMethod<
    [subjectIdHash: BytesLike, recordIdHash: BytesLike],
    [
      [boolean, boolean, string, string, bigint] & {
        exists: boolean;
        isActive: boolean;
        reporterIdHash: string;
        recordHash: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getUnacceptedFlags: TypedContractMethod<
    [subjectIdHash: BytesLike],
    [HealthRecordCore.UnacceptedFlagStructOutput[]],
    "view"
  >;

  getUserDispute: TypedContractMethod<
    [recordHash: BytesLike, userIdHash: BytesLike],
    [
      [boolean, string, bigint, bigint, string, bigint, boolean] & {
        exists: boolean;
        recordIdHash: string;
        severity: bigint;
        culpability: bigint;
        notes: string;
        createdAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getUserDisputes: TypedContractMethod<
    [userIdHash: BytesLike],
    [string[]],
    "view"
  >;

  getUserVerification: TypedContractMethod<
    [recordHash: BytesLike, userIdHash: BytesLike],
    [
      [boolean, string, bigint, bigint, boolean] & {
        exists: boolean;
        recordIdHash: string;
        level: bigint;
        createdAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getUserVerifications: TypedContractMethod<
    [userIdHash: BytesLike],
    [string[]],
    "view"
  >;

  getVerificationStats: TypedContractMethod<
    [recordHash: BytesLike],
    [[bigint, bigint] & { total: bigint; active: bigint }],
    "view"
  >;

  getVerifications: TypedContractMethod<
    [recordHash: BytesLike],
    [HealthRecordCore.VerificationStructOutput[]],
    "view"
  >;

  getVersionCount: TypedContractMethod<
    [recordIdHash: BytesLike],
    [bigint],
    "view"
  >;

  hasActiveUnacceptedFlags: TypedContractMethod<
    [subjectIdHash: BytesLike],
    [boolean],
    "view"
  >;

  hasUserDisputed: TypedContractMethod<
    [recordHash: BytesLike, userIdHash: BytesLike],
    [boolean],
    "view"
  >;

  hasUserVerified: TypedContractMethod<
    [recordHash: BytesLike, userIdHash: BytesLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [_memberRoleManager: AddressLike],
    [void],
    "nonpayable"
  >;

  isActiveSubject: TypedContractMethod<
    [recordIdHash: BytesLike, userIdHash: BytesLike],
    [boolean],
    "view"
  >;

  isHashActive: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  isSubject: TypedContractMethod<
    [recordIdHash: BytesLike, userIdHash: BytesLike],
    [boolean],
    "view"
  >;

  isSubjectActive: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [boolean],
    "view"
  >;

  isSubjectOfRecord: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [boolean],
    "view"
  >;

  memberRoleManager: TypedContractMethod<[], [string], "view">;

  modifyDispute: TypedContractMethod<
    [
      recordHash: BytesLike,
      newSeverity: BigNumberish,
      newCulpability: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  modifyVerificationLevel: TypedContractMethod<
    [recordHash: BytesLike, newLevel: BigNumberish],
    [void],
    "nonpayable"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  reanchorRecord: TypedContractMethod<
    [recordIdHash: BytesLike, subjectIdHash: BytesLike],
    [void],
    "nonpayable"
  >;

  recordIdForHash: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  recordSubjects: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  recordVersionHistory: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  retractDispute: TypedContractMethod<
    [recordHash: BytesLike],
    [void],
    "nonpayable"
  >;

  retractRecordHash: TypedContractMethod<
    [recordIdHash: BytesLike, recordHash: BytesLike],
    [void],
    "nonpayable"
  >;

  retractVerification: TypedContractMethod<
    [recordHash: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeUnacceptedFlag: TypedContractMethod<
    [subjectIdHash: BytesLike, recordIdHash: BytesLike],
    [void],
    "nonpayable"
  >;

  setMemberRoleManager: TypedContractMethod<
    [_memberRoleManager: AddressLike],
    [void],
    "nonpayable"
  >;

  subjectMedicalHistory: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  totalAnchoredRecords: TypedContractMethod<[], [bigint], "view">;

  totalDisputes: TypedContractMethod<[], [bigint], "view">;

  totalUnacceptedFlags: TypedContractMethod<[], [bigint], "view">;

  totalVerifications: TypedContractMethod<[], [bigint], "view">;

  transferAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  unacceptedFlagIndex: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [bigint],
    "view"
  >;

  unacceptedFlagsBySubject: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, string, bigint, boolean] & {
        recordIdHash: string;
        reporterIdHash: string;
        recordHash: string;
        createdAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  unanchorRecord: TypedContractMethod<
    [recordIdHash: BytesLike, subjectIdHash: BytesLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  verificationIndex: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [bigint],
    "view"
  >;

  verifications: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint, boolean] & {
        verifierIdHash: string;
        recordIdHash: string;
        level: bigint;
        createdAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  verificationsByUser: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  verifyRecord: TypedContractMethod<
    [recordIdHash: BytesLike, recordHash: BytesLike, level: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "activeUnacceptedFlagCount"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "addRecordHash"
  ): TypedContractMethod<
    [recordIdHash: BytesLike, newHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "anchorRecord"
  ): TypedContractMethod<
    [recordIdHash: BytesLike, recordHash: BytesLike, subjectIdHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "currentlyDisputed"
  ): TypedContractMethod<[arg0: BytesLike, arg1: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "currentlyVerified"
  ): TypedContractMethod<[arg0: BytesLike, arg1: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "disputeIndex"
  ): TypedContractMethod<[arg0: BytesLike, arg1: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "disputeRecord"
  ): TypedContractMethod<
    [
      recordIdHash: BytesLike,
      recordHash: BytesLike,
      severity: BigNumberish,
      culpability: BigNumberish,
      notes: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputes"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint, string, bigint, boolean] & {
        disputerIdHash: string;
        recordIdHash: string;
        severity: bigint;
        culpability: bigint;
        notes: string;
        createdAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "disputesByUser"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "doesHashExist"
  ): TypedContractMethod<[recordHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "flagUnacceptedUpdate"
  ): TypedContractMethod<
    [
      subjectIdHash: BytesLike,
      recordIdHash: BytesLike,
      reporterIdHash: BytesLike,
      recordHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getActiveRecordSubjects"
  ): TypedContractMethod<[recordIdHash: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getActiveUnacceptedFlagCount"
  ): TypedContractMethod<[subjectIdHash: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDisputeStats"
  ): TypedContractMethod<
    [recordHash: BytesLike],
    [[bigint, bigint] & { total: bigint; active: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDisputes"
  ): TypedContractMethod<
    [recordHash: BytesLike],
    [HealthRecordCore.DisputeStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecordIdForHash"
  ): TypedContractMethod<[recordHash: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRecordSubjects"
  ): TypedContractMethod<[recordIdHash: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRecordVersionHistory"
  ): TypedContractMethod<[recordIdHash: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getSubjectMedicalHistory"
  ): TypedContractMethod<[userIdHash: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getSubjectStats"
  ): TypedContractMethod<
    [recordIdHash: BytesLike],
    [[bigint, bigint] & { total: bigint; active: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalAnchoredRecords"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUnacceptedFlag"
  ): TypedContractMethod<
    [subjectIdHash: BytesLike, recordIdHash: BytesLike],
    [
      [boolean, boolean, string, string, bigint] & {
        exists: boolean;
        isActive: boolean;
        reporterIdHash: string;
        recordHash: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUnacceptedFlags"
  ): TypedContractMethod<
    [subjectIdHash: BytesLike],
    [HealthRecordCore.UnacceptedFlagStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserDispute"
  ): TypedContractMethod<
    [recordHash: BytesLike, userIdHash: BytesLike],
    [
      [boolean, string, bigint, bigint, string, bigint, boolean] & {
        exists: boolean;
        recordIdHash: string;
        severity: bigint;
        culpability: bigint;
        notes: string;
        createdAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserDisputes"
  ): TypedContractMethod<[userIdHash: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getUserVerification"
  ): TypedContractMethod<
    [recordHash: BytesLike, userIdHash: BytesLike],
    [
      [boolean, string, bigint, bigint, boolean] & {
        exists: boolean;
        recordIdHash: string;
        level: bigint;
        createdAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserVerifications"
  ): TypedContractMethod<[userIdHash: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getVerificationStats"
  ): TypedContractMethod<
    [recordHash: BytesLike],
    [[bigint, bigint] & { total: bigint; active: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVerifications"
  ): TypedContractMethod<
    [recordHash: BytesLike],
    [HealthRecordCore.VerificationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVersionCount"
  ): TypedContractMethod<[recordIdHash: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasActiveUnacceptedFlags"
  ): TypedContractMethod<[subjectIdHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasUserDisputed"
  ): TypedContractMethod<
    [recordHash: BytesLike, userIdHash: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasUserVerified"
  ): TypedContractMethod<
    [recordHash: BytesLike, userIdHash: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_memberRoleManager: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isActiveSubject"
  ): TypedContractMethod<
    [recordIdHash: BytesLike, userIdHash: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isHashActive"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isSubject"
  ): TypedContractMethod<
    [recordIdHash: BytesLike, userIdHash: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSubjectActive"
  ): TypedContractMethod<[arg0: BytesLike, arg1: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isSubjectOfRecord"
  ): TypedContractMethod<[arg0: BytesLike, arg1: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "memberRoleManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "modifyDispute"
  ): TypedContractMethod<
    [
      recordHash: BytesLike,
      newSeverity: BigNumberish,
      newCulpability: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "modifyVerificationLevel"
  ): TypedContractMethod<
    [recordHash: BytesLike, newLevel: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reanchorRecord"
  ): TypedContractMethod<
    [recordIdHash: BytesLike, subjectIdHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordIdForHash"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "recordSubjects"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordVersionHistory"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "retractDispute"
  ): TypedContractMethod<[recordHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "retractRecordHash"
  ): TypedContractMethod<
    [recordIdHash: BytesLike, recordHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "retractVerification"
  ): TypedContractMethod<[recordHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeUnacceptedFlag"
  ): TypedContractMethod<
    [subjectIdHash: BytesLike, recordIdHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMemberRoleManager"
  ): TypedContractMethod<
    [_memberRoleManager: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "subjectMedicalHistory"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalAnchoredRecords"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalDisputes"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalUnacceptedFlags"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVerifications"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unacceptedFlagIndex"
  ): TypedContractMethod<[arg0: BytesLike, arg1: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "unacceptedFlagsBySubject"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, string, bigint, boolean] & {
        recordIdHash: string;
        reporterIdHash: string;
        recordHash: string;
        createdAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "unanchorRecord"
  ): TypedContractMethod<
    [recordIdHash: BytesLike, subjectIdHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "verificationIndex"
  ): TypedContractMethod<[arg0: BytesLike, arg1: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifications"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint, boolean] & {
        verifierIdHash: string;
        recordIdHash: string;
        level: bigint;
        createdAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verificationsByUser"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyRecord"
  ): TypedContractMethod<
    [recordIdHash: BytesLike, recordHash: BytesLike, level: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AdminTransferred"
  ): TypedContractEvent<
    AdminTransferredEvent.InputTuple,
    AdminTransferredEvent.OutputTuple,
    AdminTransferredEvent.OutputObject
  >;
  getEvent(
    key: "DisputeModification"
  ): TypedContractEvent<
    DisputeModificationEvent.InputTuple,
    DisputeModificationEvent.OutputTuple,
    DisputeModificationEvent.OutputObject
  >;
  getEvent(
    key: "DisputeRetracted"
  ): TypedContractEvent<
    DisputeRetractedEvent.InputTuple,
    DisputeRetractedEvent.OutputTuple,
    DisputeRetractedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "RecordAnchored"
  ): TypedContractEvent<
    RecordAnchoredEvent.InputTuple,
    RecordAnchoredEvent.OutputTuple,
    RecordAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "RecordDisputed"
  ): TypedContractEvent<
    RecordDisputedEvent.InputTuple,
    RecordDisputedEvent.OutputTuple,
    RecordDisputedEvent.OutputObject
  >;
  getEvent(
    key: "RecordHashAdded"
  ): TypedContractEvent<
    RecordHashAddedEvent.InputTuple,
    RecordHashAddedEvent.OutputTuple,
    RecordHashAddedEvent.OutputObject
  >;
  getEvent(
    key: "RecordHashRetracted"
  ): TypedContractEvent<
    RecordHashRetractedEvent.InputTuple,
    RecordHashRetractedEvent.OutputTuple,
    RecordHashRetractedEvent.OutputObject
  >;
  getEvent(
    key: "RecordReanchored"
  ): TypedContractEvent<
    RecordReanchoredEvent.InputTuple,
    RecordReanchoredEvent.OutputTuple,
    RecordReanchoredEvent.OutputObject
  >;
  getEvent(
    key: "RecordUnanchored"
  ): TypedContractEvent<
    RecordUnanchoredEvent.InputTuple,
    RecordUnanchoredEvent.OutputTuple,
    RecordUnanchoredEvent.OutputObject
  >;
  getEvent(
    key: "RecordVerified"
  ): TypedContractEvent<
    RecordVerifiedEvent.InputTuple,
    RecordVerifiedEvent.OutputTuple,
    RecordVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "UnacceptedUpdateFlagRevoked"
  ): TypedContractEvent<
    UnacceptedUpdateFlagRevokedEvent.InputTuple,
    UnacceptedUpdateFlagRevokedEvent.OutputTuple,
    UnacceptedUpdateFlagRevokedEvent.OutputObject
  >;
  getEvent(
    key: "UnacceptedUpdateFlagged"
  ): TypedContractEvent<
    UnacceptedUpdateFlaggedEvent.InputTuple,
    UnacceptedUpdateFlaggedEvent.OutputTuple,
    UnacceptedUpdateFlaggedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationLevelModified"
  ): TypedContractEvent<
    VerificationLevelModifiedEvent.InputTuple,
    VerificationLevelModifiedEvent.OutputTuple,
    VerificationLevelModifiedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationRetracted"
  ): TypedContractEvent<
    VerificationRetractedEvent.InputTuple,
    VerificationRetractedEvent.OutputTuple,
    VerificationRetractedEvent.OutputObject
  >;

  filters: {
    "AdminTransferred(address,address,uint256)": TypedContractEvent<
      AdminTransferredEvent.InputTuple,
      AdminTransferredEvent.OutputTuple,
      AdminTransferredEvent.OutputObject
    >;
    AdminTransferred: TypedContractEvent<
      AdminTransferredEvent.InputTuple,
      AdminTransferredEvent.OutputTuple,
      AdminTransferredEvent.OutputObject
    >;

    "DisputeModification(bytes32,bytes32,uint8,uint8,uint8,uint8,uint256)": TypedContractEvent<
      DisputeModificationEvent.InputTuple,
      DisputeModificationEvent.OutputTuple,
      DisputeModificationEvent.OutputObject
    >;
    DisputeModification: TypedContractEvent<
      DisputeModificationEvent.InputTuple,
      DisputeModificationEvent.OutputTuple,
      DisputeModificationEvent.OutputObject
    >;

    "DisputeRetracted(bytes32,bytes32,uint256)": TypedContractEvent<
      DisputeRetractedEvent.InputTuple,
      DisputeRetractedEvent.OutputTuple,
      DisputeRetractedEvent.OutputObject
    >;
    DisputeRetracted: TypedContractEvent<
      DisputeRetractedEvent.InputTuple,
      DisputeRetractedEvent.OutputTuple,
      DisputeRetractedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "RecordAnchored(bytes32,bytes32,bytes32,uint256)": TypedContractEvent<
      RecordAnchoredEvent.InputTuple,
      RecordAnchoredEvent.OutputTuple,
      RecordAnchoredEvent.OutputObject
    >;
    RecordAnchored: TypedContractEvent<
      RecordAnchoredEvent.InputTuple,
      RecordAnchoredEvent.OutputTuple,
      RecordAnchoredEvent.OutputObject
    >;

    "RecordDisputed(bytes32,bytes32,bytes32,uint8,uint8,uint256)": TypedContractEvent<
      RecordDisputedEvent.InputTuple,
      RecordDisputedEvent.OutputTuple,
      RecordDisputedEvent.OutputObject
    >;
    RecordDisputed: TypedContractEvent<
      RecordDisputedEvent.InputTuple,
      RecordDisputedEvent.OutputTuple,
      RecordDisputedEvent.OutputObject
    >;

    "RecordHashAdded(bytes32,bytes32,bytes32,uint256)": TypedContractEvent<
      RecordHashAddedEvent.InputTuple,
      RecordHashAddedEvent.OutputTuple,
      RecordHashAddedEvent.OutputObject
    >;
    RecordHashAdded: TypedContractEvent<
      RecordHashAddedEvent.InputTuple,
      RecordHashAddedEvent.OutputTuple,
      RecordHashAddedEvent.OutputObject
    >;

    "RecordHashRetracted(bytes32,bytes32,uint256)": TypedContractEvent<
      RecordHashRetractedEvent.InputTuple,
      RecordHashRetractedEvent.OutputTuple,
      RecordHashRetractedEvent.OutputObject
    >;
    RecordHashRetracted: TypedContractEvent<
      RecordHashRetractedEvent.InputTuple,
      RecordHashRetractedEvent.OutputTuple,
      RecordHashRetractedEvent.OutputObject
    >;

    "RecordReanchored(bytes32,bytes32,uint256)": TypedContractEvent<
      RecordReanchoredEvent.InputTuple,
      RecordReanchoredEvent.OutputTuple,
      RecordReanchoredEvent.OutputObject
    >;
    RecordReanchored: TypedContractEvent<
      RecordReanchoredEvent.InputTuple,
      RecordReanchoredEvent.OutputTuple,
      RecordReanchoredEvent.OutputObject
    >;

    "RecordUnanchored(bytes32,bytes32,uint256)": TypedContractEvent<
      RecordUnanchoredEvent.InputTuple,
      RecordUnanchoredEvent.OutputTuple,
      RecordUnanchoredEvent.OutputObject
    >;
    RecordUnanchored: TypedContractEvent<
      RecordUnanchoredEvent.InputTuple,
      RecordUnanchoredEvent.OutputTuple,
      RecordUnanchoredEvent.OutputObject
    >;

    "RecordVerified(bytes32,bytes32,bytes32,uint8,uint256)": TypedContractEvent<
      RecordVerifiedEvent.InputTuple,
      RecordVerifiedEvent.OutputTuple,
      RecordVerifiedEvent.OutputObject
    >;
    RecordVerified: TypedContractEvent<
      RecordVerifiedEvent.InputTuple,
      RecordVerifiedEvent.OutputTuple,
      RecordVerifiedEvent.OutputObject
    >;

    "UnacceptedUpdateFlagRevoked(bytes32,bytes32,bytes32,uint256)": TypedContractEvent<
      UnacceptedUpdateFlagRevokedEvent.InputTuple,
      UnacceptedUpdateFlagRevokedEvent.OutputTuple,
      UnacceptedUpdateFlagRevokedEvent.OutputObject
    >;
    UnacceptedUpdateFlagRevoked: TypedContractEvent<
      UnacceptedUpdateFlagRevokedEvent.InputTuple,
      UnacceptedUpdateFlagRevokedEvent.OutputTuple,
      UnacceptedUpdateFlagRevokedEvent.OutputObject
    >;

    "UnacceptedUpdateFlagged(bytes32,bytes32,bytes32,bytes32,uint256)": TypedContractEvent<
      UnacceptedUpdateFlaggedEvent.InputTuple,
      UnacceptedUpdateFlaggedEvent.OutputTuple,
      UnacceptedUpdateFlaggedEvent.OutputObject
    >;
    UnacceptedUpdateFlagged: TypedContractEvent<
      UnacceptedUpdateFlaggedEvent.InputTuple,
      UnacceptedUpdateFlaggedEvent.OutputTuple,
      UnacceptedUpdateFlaggedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "VerificationLevelModified(bytes32,bytes32,uint8,uint8,uint256)": TypedContractEvent<
      VerificationLevelModifiedEvent.InputTuple,
      VerificationLevelModifiedEvent.OutputTuple,
      VerificationLevelModifiedEvent.OutputObject
    >;
    VerificationLevelModified: TypedContractEvent<
      VerificationLevelModifiedEvent.InputTuple,
      VerificationLevelModifiedEvent.OutputTuple,
      VerificationLevelModifiedEvent.OutputObject
    >;

    "VerificationRetracted(bytes32,bytes32,uint256)": TypedContractEvent<
      VerificationRetractedEvent.InputTuple,
      VerificationRetractedEvent.OutputTuple,
      VerificationRetractedEvent.OutputObject
    >;
    VerificationRetracted: TypedContractEvent<
      VerificationRetractedEvent.InputTuple,
      VerificationRetractedEvent.OutputTuple,
      VerificationRetractedEvent.OutputObject
    >;
  };
}
