//Base Belrose Fields generated by createBelroseFields Coud function
export interface BelroseFields {
  visitType: string; // e.g., "Follow-up Appointment", "Lab Results", "Imaging Study"
  title: string; // Short descriptive title (e.g., "Cardiology Follow-up")
  summary: string; // Tweet-length summary, main information a future reader would need to know
  completedDate: string; // ISO date string - the main date for this record
  provider: string; // Primary provider name
  institution: string; // Healthcare institution/facility
  patient: string; // Patient Name
  detailedNarrative: string; //detailed information on the medical interaction
}

/**
 * Request payload for Belrose Fields processing
 */
export interface BelroseFieldProcessingRequest {
  fhirData: any;
  extractedText?: string;
  originalText?: string;
  fileName?: string;
  contextText?: string;
}
