/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MemberRoleManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "acceptTrustee"
      | "addMember"
      | "addMemberBatch"
      | "admin"
      | "adminsByRecord"
      | "bootstrapDependentTrustee"
      | "changeRole"
      | "changeRoleBatch"
      | "deactivateWallet"
      | "downgradeTrusteeLevel"
      | "getAllUsers"
      | "getGuestAccess"
      | "getHealthRecordCore"
      | "getRecordAdmins"
      | "getRecordOwners"
      | "getRecordRoleStats"
      | "getRecordViewers"
      | "getRecordsByUser"
      | "getRoleDetails"
      | "getRoleDetailsByUser"
      | "getRoleGranter"
      | "getTotalRoles"
      | "getTotalUsers"
      | "getTrusteeRelationship"
      | "getUserForWallet"
      | "getUserStatus"
      | "getWalletsForUser"
      | "grantGuestAccess"
      | "grantRole"
      | "grantRoleAsTrusteeBatch"
      | "grantRoleBatch"
      | "guestAccessByRecord"
      | "hasActiveGuestAccess"
      | "hasActiveRole"
      | "hasRole"
      | "healthRecordCore"
      | "initialize"
      | "initializeRecordRole"
      | "isActiveMember"
      | "isActiveSubject"
      | "isControllerOf"
      | "isOwnerOrAdmin"
      | "isVerifiedMember"
      | "isVerifiedProvider"
      | "ownersByRecord"
      | "proposeTrustee"
      | "proxiableUUID"
      | "reactivateWallet"
      | "recordRoles"
      | "recordsByUser"
      | "revokeGuestAccess"
      | "revokeRole"
      | "revokeRoleBatch"
      | "revokeTrustee"
      | "roleGrantedBy"
      | "setHealthRecordCore"
      | "setUserStatus"
      | "totalRoles"
      | "totalUsers"
      | "transferAdmin"
      | "trusteeRelationships"
      | "updateTrusteeLevel"
      | "upgradeToAndCall"
      | "userList"
      | "userStatus"
      | "userWallets"
      | "viewersByRecord"
      | "voluntarilyLeaveOwnership"
      | "wallets"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminTransferred"
      | "GuestAccessGranted"
      | "GuestAccessRevoked"
      | "HealthRecordCoreUpdated"
      | "Initialized"
      | "MemberRegistered"
      | "MemberStatusChanged"
      | "OwnershipVoluntarilyLeft"
      | "RoleChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TrusteeAccepted"
      | "TrusteeLevelUpdated"
      | "TrusteeProposed"
      | "TrusteeRevoked"
      | "Upgraded"
      | "WalletLinked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptTrustee",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addMember",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addMemberBatch",
    values: [AddressLike[], BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "adminsByRecord",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bootstrapDependentTrustee",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "changeRole",
    values: [BytesLike, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "changeRoleBatch",
    values: [BytesLike[], AddressLike, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "downgradeTrusteeLevel",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllUsers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGuestAccess",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHealthRecordCore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordAdmins",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordOwners",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordRoleStats",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordViewers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordsByUser",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleDetails",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleDetailsByUser",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleGranter",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalRoles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalUsers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTrusteeRelationship",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserForWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWalletsForUser",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantGuestAccess",
    values: [BytesLike[], AddressLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRoleAsTrusteeBatch",
    values: [BytesLike[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRoleBatch",
    values: [BytesLike[], AddressLike, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "guestAccessByRecord",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasActiveGuestAccess",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasActiveRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "healthRecordCore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeRecordRole",
    values: [BytesLike, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isActiveMember",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isActiveSubject",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isControllerOf",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOwnerOrAdmin",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerifiedMember",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerifiedProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ownersByRecord",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeTrustee",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reactivateWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordRoles",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordsByUser",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeGuestAccess",
    values: [BytesLike[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRoleBatch",
    values: [BytesLike[], AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeTrustee",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "roleGrantedBy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setHealthRecordCore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserStatus",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRoles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalUsers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trusteeRelationships",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTrusteeLevel",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userWallets",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "viewersByRecord",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voluntarilyLeaveOwnership",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "wallets",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptTrustee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addMember", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addMemberBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "adminsByRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bootstrapDependentTrustee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "changeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeRoleBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "downgradeTrusteeLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGuestAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHealthRecordCore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordAdmins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordOwners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordRoleStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordViewers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordsByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleDetailsByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleGranter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalRoles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrusteeRelationship",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserForWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWalletsForUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantGuestAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantRoleAsTrusteeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantRoleBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "guestAccessByRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasActiveGuestAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasActiveRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "healthRecordCore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeRecordRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isActiveMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isActiveSubject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isControllerOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOwnerOrAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isVerifiedMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isVerifiedProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownersByRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeTrustee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reactivateWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordRoles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordsByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeGuestAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeRoleBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeTrustee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roleGrantedBy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHealthRecordCore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalRoles", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalUsers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trusteeRelationships",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTrusteeLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userStatus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userWallets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewersByRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voluntarilyLeaveOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wallets", data: BytesLike): Result;
}

export namespace AdminTransferredEvent {
  export type InputTuple = [
    oldAdmin: AddressLike,
    newAdmin: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    oldAdmin: string,
    newAdmin: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    oldAdmin: string;
    newAdmin: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GuestAccessGrantedEvent {
  export type InputTuple = [
    recordIdHash: BytesLike,
    grantedByIdHash: BytesLike,
    guestIdHash: BytesLike,
    guestEmailHash: BytesLike,
    expiresAt: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordIdHash: string,
    grantedByIdHash: string,
    guestIdHash: string,
    guestEmailHash: string,
    expiresAt: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordIdHash: string;
    grantedByIdHash: string;
    guestIdHash: string;
    guestEmailHash: string;
    expiresAt: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GuestAccessRevokedEvent {
  export type InputTuple = [
    recordIdHash: BytesLike,
    revokedByIdHash: BytesLike,
    guestIdHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordIdHash: string,
    revokedByIdHash: string,
    guestIdHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordIdHash: string;
    revokedByIdHash: string;
    guestIdHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HealthRecordCoreUpdatedEvent {
  export type InputTuple = [newAddress: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [newAddress: string, timestamp: bigint];
  export interface OutputObject {
    newAddress: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberRegisteredEvent {
  export type InputTuple = [
    wallet: AddressLike,
    userIdHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    wallet: string,
    userIdHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    wallet: string;
    userIdHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberStatusChangedEvent {
  export type InputTuple = [
    userIdHash: BytesLike,
    oldStatus: BigNumberish,
    newStatus: BigNumberish,
    changedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    userIdHash: string,
    oldStatus: bigint,
    newStatus: bigint,
    changedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    userIdHash: string;
    oldStatus: bigint;
    newStatus: bigint;
    changedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipVoluntarilyLeftEvent {
  export type InputTuple = [
    recordIdHash: BytesLike,
    userIdHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordIdHash: string,
    userIdHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordIdHash: string;
    userIdHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleChangedEvent {
  export type InputTuple = [
    recordIdHash: BytesLike,
    targetIdHash: BytesLike,
    oldRole: string,
    newRole: string,
    userIdHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordIdHash: string,
    targetIdHash: string,
    oldRole: string,
    newRole: string,
    userIdHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordIdHash: string;
    targetIdHash: string;
    oldRole: string;
    newRole: string;
    userIdHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    recordIdHash: BytesLike,
    targetIdHash: BytesLike,
    role: string,
    userIdHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordIdHash: string,
    targetIdHash: string,
    role: string,
    userIdHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordIdHash: string;
    targetIdHash: string;
    role: string;
    userIdHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    recordIdHash: BytesLike,
    targetIdHash: BytesLike,
    role: string,
    userIdHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordIdHash: string,
    targetIdHash: string,
    role: string,
    userIdHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordIdHash: string;
    targetIdHash: string;
    role: string;
    userIdHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrusteeAcceptedEvent {
  export type InputTuple = [
    trustorIdHash: BytesLike,
    trusteeIdHash: BytesLike,
    level: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    trustorIdHash: string,
    trusteeIdHash: string,
    level: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    trustorIdHash: string;
    trusteeIdHash: string;
    level: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrusteeLevelUpdatedEvent {
  export type InputTuple = [
    trustorIdHash: BytesLike,
    trusteeIdHash: BytesLike,
    oldLevel: BigNumberish,
    newLevel: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    trustorIdHash: string,
    trusteeIdHash: string,
    oldLevel: bigint,
    newLevel: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    trustorIdHash: string;
    trusteeIdHash: string;
    oldLevel: bigint;
    newLevel: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrusteeProposedEvent {
  export type InputTuple = [
    trustorIdHash: BytesLike,
    trusteeIdHash: BytesLike,
    level: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    trustorIdHash: string,
    trusteeIdHash: string,
    level: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    trustorIdHash: string;
    trusteeIdHash: string;
    level: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrusteeRevokedEvent {
  export type InputTuple = [
    trustorIdHash: BytesLike,
    trusteeIdHash: BytesLike,
    revokedBy: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    trustorIdHash: string,
    trusteeIdHash: string,
    revokedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    trustorIdHash: string;
    trusteeIdHash: string;
    revokedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletLinkedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    userIdHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    wallet: string,
    userIdHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    wallet: string;
    userIdHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MemberRoleManager extends BaseContract {
  connect(runner?: ContractRunner | null): MemberRoleManager;
  waitForDeployment(): Promise<this>;

  interface: MemberRoleManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  acceptTrustee: TypedContractMethod<
    [trustorIdHash: BytesLike],
    [void],
    "nonpayable"
  >;

  addMember: TypedContractMethod<
    [wallet: AddressLike, userIdHash: BytesLike],
    [void],
    "nonpayable"
  >;

  addMemberBatch: TypedContractMethod<
    [walletAddresses: AddressLike[], userIdHash: BytesLike],
    [void],
    "nonpayable"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  adminsByRecord: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  bootstrapDependentTrustee: TypedContractMethod<
    [trustorIdHash: BytesLike, trusteeIdHash: BytesLike],
    [void],
    "nonpayable"
  >;

  changeRole: TypedContractMethod<
    [recordIdHash: BytesLike, targetWallet: AddressLike, newRole: string],
    [void],
    "nonpayable"
  >;

  changeRoleBatch: TypedContractMethod<
    [
      recordIdHashes: BytesLike[],
      targetWallet: AddressLike,
      newRoles: string[]
    ],
    [void],
    "nonpayable"
  >;

  deactivateWallet: TypedContractMethod<
    [wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  downgradeTrusteeLevel: TypedContractMethod<
    [trustorIdHash: BytesLike, newLevel: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAllUsers: TypedContractMethod<[], [string[]], "view">;

  getGuestAccess: TypedContractMethod<
    [recordIdHash: BytesLike, guestIdHash: BytesLike],
    [
      [bigint, bigint, string, string] & {
        grantedAt: bigint;
        expiresAt: bigint;
        grantedByIdHash: string;
        guestEmailHash: string;
      }
    ],
    "view"
  >;

  getHealthRecordCore: TypedContractMethod<[], [string], "view">;

  getRecordAdmins: TypedContractMethod<
    [recordIdHash: BytesLike],
    [string[]],
    "view"
  >;

  getRecordOwners: TypedContractMethod<
    [recordIdHash: BytesLike],
    [string[]],
    "view"
  >;

  getRecordRoleStats: TypedContractMethod<
    [recordIdHash: BytesLike],
    [
      [bigint, bigint, bigint] & {
        ownerCount: bigint;
        adminCount: bigint;
        viewerCount: bigint;
      }
    ],
    "view"
  >;

  getRecordViewers: TypedContractMethod<
    [recordIdHash: BytesLike],
    [string[]],
    "view"
  >;

  getRecordsByUser: TypedContractMethod<
    [userIdHash: BytesLike],
    [string[]],
    "view"
  >;

  getRoleDetails: TypedContractMethod<
    [recordIdHash: BytesLike, wallet: AddressLike],
    [[string, boolean] & { role: string; isActive: boolean }],
    "view"
  >;

  getRoleDetailsByUser: TypedContractMethod<
    [recordIdHash: BytesLike, userIdHash: BytesLike],
    [[string, boolean] & { role: string; isActive: boolean }],
    "view"
  >;

  getRoleGranter: TypedContractMethod<
    [recordIdHash: BytesLike, userIdHash: BytesLike],
    [string],
    "view"
  >;

  getTotalRoles: TypedContractMethod<[], [bigint], "view">;

  getTotalUsers: TypedContractMethod<[], [bigint], "view">;

  getTrusteeRelationship: TypedContractMethod<
    [trustorIdHash: BytesLike, trusteeIdHash: BytesLike],
    [[bigint, bigint] & { status: bigint; level: bigint }],
    "view"
  >;

  getUserForWallet: TypedContractMethod<
    [wallet: AddressLike],
    [string],
    "view"
  >;

  getUserStatus: TypedContractMethod<[userIdHash: BytesLike], [bigint], "view">;

  getWalletsForUser: TypedContractMethod<
    [userIdHash: BytesLike],
    [string[]],
    "view"
  >;

  grantGuestAccess: TypedContractMethod<
    [
      recordIdHashes: BytesLike[],
      guestWallet: AddressLike,
      guestIdHash: BytesLike,
      guestEmailHash: BytesLike,
      durationSeconds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  grantRole: TypedContractMethod<
    [recordIdHash: BytesLike, targetWallet: AddressLike, role: string],
    [void],
    "nonpayable"
  >;

  grantRoleAsTrusteeBatch: TypedContractMethod<
    [recordIdHashes: BytesLike[], trustorIdHash: BytesLike],
    [void],
    "nonpayable"
  >;

  grantRoleBatch: TypedContractMethod<
    [recordIdHashes: BytesLike[], targetWallet: AddressLike, roles: string[]],
    [void],
    "nonpayable"
  >;

  guestAccessByRecord: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [
      [bigint, bigint, string, string] & {
        grantedAt: bigint;
        expiresAt: bigint;
        grantedByIdHash: string;
        guestEmailHash: string;
      }
    ],
    "view"
  >;

  hasActiveGuestAccess: TypedContractMethod<
    [recordIdHash: BytesLike, guestIdHash: BytesLike],
    [boolean],
    "view"
  >;

  hasActiveRole: TypedContractMethod<
    [recordIdHash: BytesLike, wallet: AddressLike],
    [boolean],
    "view"
  >;

  hasRole: TypedContractMethod<
    [recordIdHash: BytesLike, wallet: AddressLike, role: string],
    [boolean],
    "view"
  >;

  healthRecordCore: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<[], [void], "nonpayable">;

  initializeRecordRole: TypedContractMethod<
    [recordIdHash: BytesLike, targetWallet: AddressLike, role: string],
    [void],
    "nonpayable"
  >;

  isActiveMember: TypedContractMethod<[wallet: AddressLike], [boolean], "view">;

  isActiveSubject: TypedContractMethod<
    [recordIdHash: BytesLike, userIdHash: BytesLike],
    [boolean],
    "view"
  >;

  isControllerOf: TypedContractMethod<
    [trustorIdHash: BytesLike, trusteeIdHash: BytesLike],
    [boolean],
    "view"
  >;

  isOwnerOrAdmin: TypedContractMethod<
    [recordIdHash: BytesLike, wallet: AddressLike],
    [boolean],
    "view"
  >;

  isVerifiedMember: TypedContractMethod<
    [wallet: AddressLike],
    [boolean],
    "view"
  >;

  isVerifiedProvider: TypedContractMethod<
    [wallet: AddressLike],
    [boolean],
    "view"
  >;

  ownersByRecord: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  proposeTrustee: TypedContractMethod<
    [trusteeIdHash: BytesLike, level: BigNumberish],
    [void],
    "nonpayable"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  reactivateWallet: TypedContractMethod<
    [wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  recordRoles: TypedContractMethod<
    [arg0: BytesLike],
    [[string, boolean] & { role: string; isActive: boolean }],
    "view"
  >;

  recordsByUser: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  revokeGuestAccess: TypedContractMethod<
    [recordIdHashes: BytesLike[], guestIdHash: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [recordIdHash: BytesLike, targetWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRoleBatch: TypedContractMethod<
    [recordIdHashes: BytesLike[], targetWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeTrustee: TypedContractMethod<
    [trustorIdHash: BytesLike, trusteeIdHash: BytesLike],
    [void],
    "nonpayable"
  >;

  roleGrantedBy: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  setHealthRecordCore: TypedContractMethod<
    [_healthRecordCore: AddressLike],
    [void],
    "nonpayable"
  >;

  setUserStatus: TypedContractMethod<
    [userIdHash: BytesLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalRoles: TypedContractMethod<[], [bigint], "view">;

  totalUsers: TypedContractMethod<[], [bigint], "view">;

  transferAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  trusteeRelationships: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [[bigint, bigint] & { status: bigint; level: bigint }],
    "view"
  >;

  updateTrusteeLevel: TypedContractMethod<
    [trusteeIdHash: BytesLike, newLevel: BigNumberish],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  userList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  userStatus: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  userWallets: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  viewersByRecord: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  voluntarilyLeaveOwnership: TypedContractMethod<
    [recordIdHash: BytesLike],
    [void],
    "nonpayable"
  >;

  wallets: TypedContractMethod<
    [arg0: AddressLike],
    [[string, boolean] & { userIdHash: string; isWalletActive: boolean }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptTrustee"
  ): TypedContractMethod<[trustorIdHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addMember"
  ): TypedContractMethod<
    [wallet: AddressLike, userIdHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addMemberBatch"
  ): TypedContractMethod<
    [walletAddresses: AddressLike[], userIdHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "adminsByRecord"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "bootstrapDependentTrustee"
  ): TypedContractMethod<
    [trustorIdHash: BytesLike, trusteeIdHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "changeRole"
  ): TypedContractMethod<
    [recordIdHash: BytesLike, targetWallet: AddressLike, newRole: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "changeRoleBatch"
  ): TypedContractMethod<
    [
      recordIdHashes: BytesLike[],
      targetWallet: AddressLike,
      newRoles: string[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivateWallet"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "downgradeTrusteeLevel"
  ): TypedContractMethod<
    [trustorIdHash: BytesLike, newLevel: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllUsers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getGuestAccess"
  ): TypedContractMethod<
    [recordIdHash: BytesLike, guestIdHash: BytesLike],
    [
      [bigint, bigint, string, string] & {
        grantedAt: bigint;
        expiresAt: bigint;
        grantedByIdHash: string;
        guestEmailHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getHealthRecordCore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRecordAdmins"
  ): TypedContractMethod<[recordIdHash: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRecordOwners"
  ): TypedContractMethod<[recordIdHash: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRecordRoleStats"
  ): TypedContractMethod<
    [recordIdHash: BytesLike],
    [
      [bigint, bigint, bigint] & {
        ownerCount: bigint;
        adminCount: bigint;
        viewerCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecordViewers"
  ): TypedContractMethod<[recordIdHash: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRecordsByUser"
  ): TypedContractMethod<[userIdHash: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRoleDetails"
  ): TypedContractMethod<
    [recordIdHash: BytesLike, wallet: AddressLike],
    [[string, boolean] & { role: string; isActive: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleDetailsByUser"
  ): TypedContractMethod<
    [recordIdHash: BytesLike, userIdHash: BytesLike],
    [[string, boolean] & { role: string; isActive: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleGranter"
  ): TypedContractMethod<
    [recordIdHash: BytesLike, userIdHash: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalRoles"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalUsers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTrusteeRelationship"
  ): TypedContractMethod<
    [trustorIdHash: BytesLike, trusteeIdHash: BytesLike],
    [[bigint, bigint] & { status: bigint; level: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserForWallet"
  ): TypedContractMethod<[wallet: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getUserStatus"
  ): TypedContractMethod<[userIdHash: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getWalletsForUser"
  ): TypedContractMethod<[userIdHash: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "grantGuestAccess"
  ): TypedContractMethod<
    [
      recordIdHashes: BytesLike[],
      guestWallet: AddressLike,
      guestIdHash: BytesLike,
      guestEmailHash: BytesLike,
      durationSeconds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [recordIdHash: BytesLike, targetWallet: AddressLike, role: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantRoleAsTrusteeBatch"
  ): TypedContractMethod<
    [recordIdHashes: BytesLike[], trustorIdHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantRoleBatch"
  ): TypedContractMethod<
    [recordIdHashes: BytesLike[], targetWallet: AddressLike, roles: string[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "guestAccessByRecord"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [
      [bigint, bigint, string, string] & {
        grantedAt: bigint;
        expiresAt: bigint;
        grantedByIdHash: string;
        guestEmailHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasActiveGuestAccess"
  ): TypedContractMethod<
    [recordIdHash: BytesLike, guestIdHash: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasActiveRole"
  ): TypedContractMethod<
    [recordIdHash: BytesLike, wallet: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [recordIdHash: BytesLike, wallet: AddressLike, role: string],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "healthRecordCore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initializeRecordRole"
  ): TypedContractMethod<
    [recordIdHash: BytesLike, targetWallet: AddressLike, role: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isActiveMember"
  ): TypedContractMethod<[wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isActiveSubject"
  ): TypedContractMethod<
    [recordIdHash: BytesLike, userIdHash: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isControllerOf"
  ): TypedContractMethod<
    [trustorIdHash: BytesLike, trusteeIdHash: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isOwnerOrAdmin"
  ): TypedContractMethod<
    [recordIdHash: BytesLike, wallet: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isVerifiedMember"
  ): TypedContractMethod<[wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVerifiedProvider"
  ): TypedContractMethod<[wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "ownersByRecord"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposeTrustee"
  ): TypedContractMethod<
    [trusteeIdHash: BytesLike, level: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reactivateWallet"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recordRoles"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [[string, boolean] & { role: string; isActive: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordsByUser"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeGuestAccess"
  ): TypedContractMethod<
    [recordIdHashes: BytesLike[], guestIdHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [recordIdHash: BytesLike, targetWallet: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRoleBatch"
  ): TypedContractMethod<
    [recordIdHashes: BytesLike[], targetWallet: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeTrustee"
  ): TypedContractMethod<
    [trustorIdHash: BytesLike, trusteeIdHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "roleGrantedBy"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "setHealthRecordCore"
  ): TypedContractMethod<
    [_healthRecordCore: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setUserStatus"
  ): TypedContractMethod<
    [userIdHash: BytesLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalRoles"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalUsers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trusteeRelationships"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [[bigint, bigint] & { status: bigint; level: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateTrusteeLevel"
  ): TypedContractMethod<
    [trusteeIdHash: BytesLike, newLevel: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "userList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "userStatus"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userWallets"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "viewersByRecord"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "voluntarilyLeaveOwnership"
  ): TypedContractMethod<[recordIdHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "wallets"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[string, boolean] & { userIdHash: string; isWalletActive: boolean }],
    "view"
  >;

  getEvent(
    key: "AdminTransferred"
  ): TypedContractEvent<
    AdminTransferredEvent.InputTuple,
    AdminTransferredEvent.OutputTuple,
    AdminTransferredEvent.OutputObject
  >;
  getEvent(
    key: "GuestAccessGranted"
  ): TypedContractEvent<
    GuestAccessGrantedEvent.InputTuple,
    GuestAccessGrantedEvent.OutputTuple,
    GuestAccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "GuestAccessRevoked"
  ): TypedContractEvent<
    GuestAccessRevokedEvent.InputTuple,
    GuestAccessRevokedEvent.OutputTuple,
    GuestAccessRevokedEvent.OutputObject
  >;
  getEvent(
    key: "HealthRecordCoreUpdated"
  ): TypedContractEvent<
    HealthRecordCoreUpdatedEvent.InputTuple,
    HealthRecordCoreUpdatedEvent.OutputTuple,
    HealthRecordCoreUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MemberRegistered"
  ): TypedContractEvent<
    MemberRegisteredEvent.InputTuple,
    MemberRegisteredEvent.OutputTuple,
    MemberRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "MemberStatusChanged"
  ): TypedContractEvent<
    MemberStatusChangedEvent.InputTuple,
    MemberStatusChangedEvent.OutputTuple,
    MemberStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipVoluntarilyLeft"
  ): TypedContractEvent<
    OwnershipVoluntarilyLeftEvent.InputTuple,
    OwnershipVoluntarilyLeftEvent.OutputTuple,
    OwnershipVoluntarilyLeftEvent.OutputObject
  >;
  getEvent(
    key: "RoleChanged"
  ): TypedContractEvent<
    RoleChangedEvent.InputTuple,
    RoleChangedEvent.OutputTuple,
    RoleChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TrusteeAccepted"
  ): TypedContractEvent<
    TrusteeAcceptedEvent.InputTuple,
    TrusteeAcceptedEvent.OutputTuple,
    TrusteeAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "TrusteeLevelUpdated"
  ): TypedContractEvent<
    TrusteeLevelUpdatedEvent.InputTuple,
    TrusteeLevelUpdatedEvent.OutputTuple,
    TrusteeLevelUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TrusteeProposed"
  ): TypedContractEvent<
    TrusteeProposedEvent.InputTuple,
    TrusteeProposedEvent.OutputTuple,
    TrusteeProposedEvent.OutputObject
  >;
  getEvent(
    key: "TrusteeRevoked"
  ): TypedContractEvent<
    TrusteeRevokedEvent.InputTuple,
    TrusteeRevokedEvent.OutputTuple,
    TrusteeRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "WalletLinked"
  ): TypedContractEvent<
    WalletLinkedEvent.InputTuple,
    WalletLinkedEvent.OutputTuple,
    WalletLinkedEvent.OutputObject
  >;

  filters: {
    "AdminTransferred(address,address,uint256)": TypedContractEvent<
      AdminTransferredEvent.InputTuple,
      AdminTransferredEvent.OutputTuple,
      AdminTransferredEvent.OutputObject
    >;
    AdminTransferred: TypedContractEvent<
      AdminTransferredEvent.InputTuple,
      AdminTransferredEvent.OutputTuple,
      AdminTransferredEvent.OutputObject
    >;

    "GuestAccessGranted(bytes32,bytes32,bytes32,bytes32,uint256,uint256)": TypedContractEvent<
      GuestAccessGrantedEvent.InputTuple,
      GuestAccessGrantedEvent.OutputTuple,
      GuestAccessGrantedEvent.OutputObject
    >;
    GuestAccessGranted: TypedContractEvent<
      GuestAccessGrantedEvent.InputTuple,
      GuestAccessGrantedEvent.OutputTuple,
      GuestAccessGrantedEvent.OutputObject
    >;

    "GuestAccessRevoked(bytes32,bytes32,bytes32,uint256)": TypedContractEvent<
      GuestAccessRevokedEvent.InputTuple,
      GuestAccessRevokedEvent.OutputTuple,
      GuestAccessRevokedEvent.OutputObject
    >;
    GuestAccessRevoked: TypedContractEvent<
      GuestAccessRevokedEvent.InputTuple,
      GuestAccessRevokedEvent.OutputTuple,
      GuestAccessRevokedEvent.OutputObject
    >;

    "HealthRecordCoreUpdated(address,uint256)": TypedContractEvent<
      HealthRecordCoreUpdatedEvent.InputTuple,
      HealthRecordCoreUpdatedEvent.OutputTuple,
      HealthRecordCoreUpdatedEvent.OutputObject
    >;
    HealthRecordCoreUpdated: TypedContractEvent<
      HealthRecordCoreUpdatedEvent.InputTuple,
      HealthRecordCoreUpdatedEvent.OutputTuple,
      HealthRecordCoreUpdatedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MemberRegistered(address,bytes32,uint256)": TypedContractEvent<
      MemberRegisteredEvent.InputTuple,
      MemberRegisteredEvent.OutputTuple,
      MemberRegisteredEvent.OutputObject
    >;
    MemberRegistered: TypedContractEvent<
      MemberRegisteredEvent.InputTuple,
      MemberRegisteredEvent.OutputTuple,
      MemberRegisteredEvent.OutputObject
    >;

    "MemberStatusChanged(bytes32,uint8,uint8,address,uint256)": TypedContractEvent<
      MemberStatusChangedEvent.InputTuple,
      MemberStatusChangedEvent.OutputTuple,
      MemberStatusChangedEvent.OutputObject
    >;
    MemberStatusChanged: TypedContractEvent<
      MemberStatusChangedEvent.InputTuple,
      MemberStatusChangedEvent.OutputTuple,
      MemberStatusChangedEvent.OutputObject
    >;

    "OwnershipVoluntarilyLeft(bytes32,bytes32,uint256)": TypedContractEvent<
      OwnershipVoluntarilyLeftEvent.InputTuple,
      OwnershipVoluntarilyLeftEvent.OutputTuple,
      OwnershipVoluntarilyLeftEvent.OutputObject
    >;
    OwnershipVoluntarilyLeft: TypedContractEvent<
      OwnershipVoluntarilyLeftEvent.InputTuple,
      OwnershipVoluntarilyLeftEvent.OutputTuple,
      OwnershipVoluntarilyLeftEvent.OutputObject
    >;

    "RoleChanged(bytes32,bytes32,string,string,bytes32,uint256)": TypedContractEvent<
      RoleChangedEvent.InputTuple,
      RoleChangedEvent.OutputTuple,
      RoleChangedEvent.OutputObject
    >;
    RoleChanged: TypedContractEvent<
      RoleChangedEvent.InputTuple,
      RoleChangedEvent.OutputTuple,
      RoleChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,bytes32,string,bytes32,uint256)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,bytes32,string,bytes32,uint256)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TrusteeAccepted(bytes32,bytes32,uint8,uint256)": TypedContractEvent<
      TrusteeAcceptedEvent.InputTuple,
      TrusteeAcceptedEvent.OutputTuple,
      TrusteeAcceptedEvent.OutputObject
    >;
    TrusteeAccepted: TypedContractEvent<
      TrusteeAcceptedEvent.InputTuple,
      TrusteeAcceptedEvent.OutputTuple,
      TrusteeAcceptedEvent.OutputObject
    >;

    "TrusteeLevelUpdated(bytes32,bytes32,uint8,uint8,uint256)": TypedContractEvent<
      TrusteeLevelUpdatedEvent.InputTuple,
      TrusteeLevelUpdatedEvent.OutputTuple,
      TrusteeLevelUpdatedEvent.OutputObject
    >;
    TrusteeLevelUpdated: TypedContractEvent<
      TrusteeLevelUpdatedEvent.InputTuple,
      TrusteeLevelUpdatedEvent.OutputTuple,
      TrusteeLevelUpdatedEvent.OutputObject
    >;

    "TrusteeProposed(bytes32,bytes32,uint8,uint256)": TypedContractEvent<
      TrusteeProposedEvent.InputTuple,
      TrusteeProposedEvent.OutputTuple,
      TrusteeProposedEvent.OutputObject
    >;
    TrusteeProposed: TypedContractEvent<
      TrusteeProposedEvent.InputTuple,
      TrusteeProposedEvent.OutputTuple,
      TrusteeProposedEvent.OutputObject
    >;

    "TrusteeRevoked(bytes32,bytes32,bytes32,uint256)": TypedContractEvent<
      TrusteeRevokedEvent.InputTuple,
      TrusteeRevokedEvent.OutputTuple,
      TrusteeRevokedEvent.OutputObject
    >;
    TrusteeRevoked: TypedContractEvent<
      TrusteeRevokedEvent.InputTuple,
      TrusteeRevokedEvent.OutputTuple,
      TrusteeRevokedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "WalletLinked(address,bytes32,uint256)": TypedContractEvent<
      WalletLinkedEvent.InputTuple,
      WalletLinkedEvent.OutputTuple,
      WalletLinkedEvent.OutputObject
    >;
    WalletLinked: TypedContractEvent<
      WalletLinkedEvent.InputTuple,
      WalletLinkedEvent.OutputTuple,
      WalletLinkedEvent.OutputObject
    >;
  };
}
