// /features/Auth/components/AlphaGateScreen.tsx
//
// Two-step pre-registration gate:
//   Step 1 — enter email → check invites collection
//     ├── approved  → show Step 2 (code entry)
//     └── not found / not approved → send to WaitlistForm
//   Step 2 — enter invite code → code matches → proceed to RegistrationForm
//
// The invite code lives on the invites/{email} doc as the `code` field.
// Format: XXXX-XXXX-XXXX-XXXX (generated by generateInviteCode util, see setup guide)

import React, { useState, useRef, useEffect } from 'react';
import { getFirestore, doc, getDoc } from 'firebase/firestore';
import { ArrowRight, ArrowLeft, Loader2, KeyRound, Pickaxe, HardHat } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { toast } from 'sonner';
import { useNavigate } from 'react-router-dom';

interface AlphaGateScreenProps {
  onApproved: (email: string) => void; // code verified → go to RegistrationForm
  onNotApproved: (email: string) => void; // no invite / not approved → go to WaitlistForm
  onSwitchToLogin: () => void;
}

type GateStep = 'email' | 'code';
type CheckState = 'idle' | 'checking' | 'transitioning';

// Strip formatting for comparison — codes are stored unformatted in Firestore
const normaliseCode = (raw: string) => raw.toUpperCase().replace(/[^A-Z0-9]/g, '');

const AlphaGateScreen: React.FC<AlphaGateScreenProps> = ({
  onApproved,
  onNotApproved,
  onSwitchToLogin,
}) => {
  const navigate = useNavigate();
  const [step, setStep] = useState<GateStep>('email');
  const [email, setEmail] = useState('');
  const [code, setCode] = useState('');
  const [checkState, setCheckState] = useState<CheckState>('idle');
  const [error, setError] = useState('');

  // Store the expected code after step 1 so step 2 can compare client-side.
  const expectedCodeRef = useRef<string>('');
  const codeInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (step === 'code') codeInputRef.current?.focus();
  }, [step]);

  // ── Step 1: check email ──────────────────────────────────────────────────
  const handleCheckEmail = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    const normalised = email.trim().toLowerCase();
    if (!normalised || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalised)) {
      setError('Please enter a valid email address.');
      return;
    }

    setCheckState('checking');

    try {
      const db = getFirestore();
      const inviteSnap = await getDoc(doc(db, 'invites', normalised));

      if (inviteSnap.exists()) {
        const data = inviteSnap.data();

        if (data.registeredUserId) {
          setCheckState('idle');
          toast.info('This email already has a Belrose account.', {
            description: 'Please sign in instead.',
          });
          onSwitchToLogin();
          return;
        }

        if (data.approved === true && data.code) {
          // Stash the expected code and move to step 2
          expectedCodeRef.current = normaliseCode(data.code);
          setCheckState('idle');
          setStep('code');
          return;
        }
      }

      // No invite or not yet approved → waitlist
      setCheckState('transitioning');
      setTimeout(() => onNotApproved(normalised), 500);
    } catch (err) {
      console.error('Error checking invite status:', err);
      setError('Something went wrong. Please try again.');
      setCheckState('idle');
    }
  };

  // ── Step 2: verify code ──────────────────────────────────────────────────
  const handleVerifyCode = (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    const entered = normaliseCode(code);

    if (entered.length < 16) {
      setError('Please enter your full invite code.');
      return;
    }

    if (entered !== expectedCodeRef.current) {
      setError("That code doesn't match. Double-check your approval email.");
      return;
    }

    setCheckState('transitioning');
    setTimeout(() => onApproved(email.trim().toLowerCase()), 500);
  };

  // Auto-format code input as user types: XXXX-XXXX-XXXX-XXXX
  const handleCodeChange = (raw: string) => {
    const clean = raw
      .toUpperCase()
      .replace(/[^A-Z0-9]/g, '')
      .slice(0, 16);
    const formatted = clean.match(/.{1,4}/g)?.join('-') ?? clean;
    setCode(formatted);
  };

  const isChecking = checkState === 'checking';
  const isTransitioning = checkState === 'transitioning';
  const isDisabled = isChecking || isTransitioning;

  return (
    <div className="min-h-screen bg-secondary flex items-center justify-center p-4">
      <div className="w-full max-w-md">
        {/* Back button — sits above the card, matches LoginForm style */}
        <button
          type="button"
          onClick={() => navigate(-1)}
          className="flex items-center space-x-2 text-foreground hover:text-primary mb-2 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back</span>
        </button>

        <div className="bg-white rounded-2xl shadow-2xl overflow-hidden">
          {/* Header — changes between steps */}
          <div className="bg-primary px-8 pt-10 pb-8">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 rounded-full bg-complement-4 flex items-center justify-center">
                {step === 'email' ? (
                  <HardHat className="w-5 h-5 text-primary" />
                ) : (
                  <KeyRound className="w-5 h-5 text-primary" />
                )}
              </div>
              <span className="text-complement-4 text-sm font-medium tracking-wide uppercase">
                {step === 'email' ? 'Alpha Access' : 'Enter Invite Code'}
              </span>
            </div>

            {step === 'email' ? (
              <>
                <h1 className="flex items-center justify-center gap-2 text-3xl font-bold text-secondary leading-tight">
                  Work in Progress
                  <Pickaxe />
                </h1>
                <p className="text-secondary/70 mt-3 text-sm leading-relaxed">
                  Belrose Health is in private alpha. Enter your email to check if you have access,
                  or join the waitlist.
                </p>
              </>
            ) : (
              <>
                <h1 className="text-3xl font-bold text-secondary leading-tight">
                  Check your email
                </h1>
                <p className="text-secondary/70 mt-3 text-sm leading-relaxed">
                  We sent an invite code to{' '}
                  <span className="text-secondary font-medium">{email}</span>. Enter it below to
                  continue.
                </p>
              </>
            )}
          </div>

          {/* Form body */}
          <div className="px-8 py-8">
            {/* Step 1: Email */}
            {step === 'email' && (
              <form onSubmit={handleCheckEmail} className="space-y-4">
                <div>
                  <label
                    htmlFor="alpha-email"
                    className="block text-sm font-medium text-gray-700 mb-1.5"
                  >
                    Email address
                  </label>
                  <input
                    id="alpha-email"
                    type="email"
                    value={email}
                    onChange={e => setEmail(e.target.value)}
                    placeholder="you@example.com"
                    disabled={isDisabled}
                    className="w-full px-4 py-3 rounded-xl border border-gray-200 bg-gray-50
                               text-gray-900 placeholder:text-gray-400
                               focus:outline-none focus:ring-2 focus:ring-complement-4 focus:border-transparent
                               disabled:opacity-60 transition"
                  />
                  {error && <p className="mt-2 text-sm text-destructive">{error}</p>}
                </div>

                <Button
                  type="submit"
                  disabled={isDisabled || !email.trim()}
                  className="w-full py-3 rounded-xl flex items-center justify-center gap-2
                             disabled:opacity-50 disabled:cursor-not-allowed transition-all"
                >
                  {isChecking ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" />
                      <span>Checking…</span>
                    </>
                  ) : isTransitioning ? (
                    <span>Redirecting…</span>
                  ) : (
                    <>
                      <span>Check my access</span>
                      <ArrowRight className="w-4 h-4" />
                    </>
                  )}
                </Button>
              </form>
            )}

            {/* Step 2: Invite code */}
            {step === 'code' && (
              <form onSubmit={handleVerifyCode} className="space-y-4">
                <div>
                  <label
                    htmlFor="invite-code"
                    className="block text-sm font-medium text-gray-700 mb-1.5"
                  >
                    Invite code
                  </label>
                  <input
                    id="invite-code"
                    ref={codeInputRef}
                    type="text"
                    value={code}
                    onChange={e => handleCodeChange(e.target.value)}
                    placeholder="XXXX-XXXX-XXXX-XXXX"
                    disabled={isDisabled}
                    spellCheck={false}
                    autoComplete="off"
                    className="w-full px-4 py-3 rounded-xl border border-gray-200 bg-gray-50
                               text-gray-900 placeholder:text-gray-400
                               font-mono tracking-widest text-center text-lg
                               focus:outline-none focus:ring-2 focus:ring-complement-4 focus:border-transparent
                               disabled:opacity-60 transition"
                  />
                  {error && <p className="mt-2 text-sm text-destructive">{error}</p>}
                  <p className="mt-2 text-xs text-gray-400">
                    Can't find your code? Check your spam folder, or{' '}
                    <button
                      type="button"
                      onClick={() => onNotApproved(email.trim().toLowerCase())}
                      className="text-complement-4 hover:underline"
                    >
                      join the waitlist
                    </button>
                    .
                  </p>
                </div>

                <div className="flex gap-3">
                  <Button
                    type="button"
                    onClick={() => {
                      setStep('email');
                      setCode('');
                      setError('');
                    }}
                    disabled={isDisabled}
                    className="px-4 py-3 rounded-xl disabled:opacity-50"
                  >
                    <ArrowLeft className="w-4 h-4" />
                  </Button>
                  <Button
                    type="submit"
                    disabled={isDisabled || normaliseCode(code).length < 16}
                    className="flex-1 py-3 rounded-xl flex items-center justify-center gap-2
                               disabled:opacity-50 disabled:cursor-not-allowed transition-all"
                  >
                    {isTransitioning ? (
                      <>
                        <Loader2 className="w-4 h-4 animate-spin" />
                        <span>Verifying…</span>
                      </>
                    ) : (
                      <>
                        <span>Verify & continue</span>
                        <ArrowRight className="w-4 h-4" />
                      </>
                    )}
                  </Button>
                </div>
              </form>
            )}

            {/* Login link */}
            <div className="flex items-center gap-3 my-6">
              <div className="flex-1 h-px bg-gray-100" />
              <span className="text-xs text-gray-400">or</span>
              <div className="flex-1 h-px bg-gray-100" />
            </div>
            <p className="text-center text-sm text-gray-500">
              Already have an account?{' '}
              <button
                type="button"
                onClick={onSwitchToLogin}
                className="text-complement-4 font-medium hover:underline transition-colors"
              >
                Sign in
              </button>
            </p>
          </div>
        </div>

        <p className="text-center text-xs text-gray-400 mt-6 leading-relaxed">
          Belrose keeps your health data private and encrypted.
          <br />
          We will never sell your information.
        </p>
      </div>
    </div>
  );
};

export default AlphaGateScreen;
