/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  MemberRoleManagerInterface,
  MemberRoleManagerInterfaceInterface,
} from "../../../smartContracts/HealthRecordCore.sol/MemberRoleManagerInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "subjectIdHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "recordIdHash",
        type: "bytes32",
      },
    ],
    name: "extendTrusteeGrantsOnAnchor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
    ],
    name: "getUserForWallet",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "recordIdHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
    ],
    name: "hasActiveRole",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "recordIdHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
      {
        internalType: "string",
        name: "role",
        type: "string",
      },
    ],
    name: "hasRole",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
    ],
    name: "isActiveMember",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "trustorIdHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "trusteeIdHash",
        type: "bytes32",
      },
    ],
    name: "isControllerOf",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "recordIdHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
    ],
    name: "isOwnerOrAdmin",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
    ],
    name: "isVerifiedMember",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "subjectIdHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "recordIdHash",
        type: "bytes32",
      },
    ],
    name: "retractTrusteeGrantsOnUnanchor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class MemberRoleManagerInterface__factory {
  static readonly abi = _abi;
  static createInterface(): MemberRoleManagerInterfaceInterface {
    return new Interface(_abi) as MemberRoleManagerInterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MemberRoleManagerInterface {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MemberRoleManagerInterface;
  }
}
