"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MessageHashUtils__factory = exports.ECDSA__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ECDSA__factory_1 = require("./ECDSA__factory");
Object.defineProperty(exports, "ECDSA__factory", { enumerable: true, get: function () { return ECDSA__factory_1.ECDSA__factory; } });
var MessageHashUtils__factory_1 = require("./MessageHashUtils__factory");
Object.defineProperty(exports, "MessageHashUtils__factory", { enumerable: true, get: function () { return MessageHashUtils__factory_1.MessageHashUtils__factory; } });
//# sourceMappingURL=index.js.map