"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MessageHashUtils__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [],
        name: "ERC5267ExtensionsNotSupported",
        type: "error",
    },
];
const _bytecode = "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212203f7e025c34e9de8a4c2a7d891c33911b00a3f3ddf5d2d910837b82ffe1e3b75c64736f6c63430008180033";
const isSuperArgs = (xs) => xs.length > 1;
class MessageHashUtils__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    connect(runner) {
        return super.connect(runner);
    }
    static createInterface() {
        return new ethers_1.Interface(_abi);
    }
    static connect(address, runner) {
        return new ethers_1.Contract(address, _abi, runner);
    }
}
exports.MessageHashUtils__factory = MessageHashUtils__factory;
MessageHashUtils__factory.bytecode = _bytecode;
MessageHashUtils__factory.abi = _abi;
//# sourceMappingURL=MessageHashUtils__factory.js.map